### ISSUE TITLE
Learn from Inventory+

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#101]
~~Add the necessary API functions and hooks to support Inventory+:~~
https://foundryvtt.com/packages/inventory-plus
https://github.com/p4535992/foundryvtt-inventory-plus

With the introduction of dnd5e 3.0.0, there are now containers available to house items and even support weightlessness.
Tidy will support containers in 3.0.0, but it should also learn from the community's love of Inventory+ and ensure that some quality of life features from Inventory+ make their way to Tidy in a form that suits this sheets module.

Idea for custom item sections: https://discord.com/channels/1167985253072257115/1202310765500186695/1202662891291934820

Idea: clicking add on a custom section will prompt the user with the Create Item dialog, and upon confirming, the item is added with its section set to the custom section where the add button was clicked. So, Inventory+ style.
https://discord.com/channels/1167985253072257115/1202310765500186695/1202682049622835291

Allow the user to specify empty sections from the sheet and not have to do it from the item.

## Reference

https://discord.com/channels/1167985253072257115/1202310765500186695

**Comment by KonteiKeisei** [comment]
Be still my beating heart......

**Comment by kgar** [comment]
Resolved by #507

**Comment by kgar** [comment]
Closing this because all lessons learned from inv+ are now spread over several github issues in the Native CCSS milestone.
