### ISSUE TITLE
Crash Tracking and Training module compatibility 

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#102]
https://foundryvtt.com/packages/5e-training
https://github.com/crash1115/5e-training

**Comment by kgar** [comment]
Related to #37

**Comment by crash1115** [comment]
Hey that's me. I don't maintain the module anymore; someone else has taken it over and rebranded it.

Still, I'll probably take the time to do a small update just for the folks who still use my version, so if you need help/input/whatever, lemme know.

**Comment by kgar** [comment]
Awesome! Thanks Crash! I will do my best to make it a minimal PR to the code base.

**Comment by kgar** [comment]
That API is finally ready: https://kgar.github.io/foundry-vtt-tidy-5e-sheets/classes/Tidy5eSheetsApi.html#registerCharacterTab

I recently did the PR for downtime dnd5e, the spiritual successor: https://github.com/p4535992/foundryvtt-downtime-dnd5e/pull/6

If you are interested in doing the update, there is some inspiration in the downtime dnd5e PR. With that said, I did some heavy CSS refactoring in that module. The main takeaway is to extract `training-section-contents.html` out of `training-section.html` and then just register `training-section-contents.html`, leaving the tab div out.

That PR has some extra things because I was also fixing a few Foundry v12 warnings and a bug, as well as adding some Tidy 5e rewrite CSS support.

**Comment by crash1115** [comment]
Okay, I'm alive again. I'll be taking a look this week/next week to see what I gotta do on my side for the folks still using my version. Thanks for the docs/PR link, appreciate it!

**Comment by kgar** [comment]
Welcome back!

**Comment by crash1115** [comment]
Just an update; 3.0 threw a big ol wrench in the works; I'm focusing on that first, but the CSS refactoring coming from that should hopefully make this relatively painless.

**Comment by kgar** [comment]
I was saying to the same thing in other github issues. 
The wrench is large, but it's a cool wrench!
I'm getting Tidy to V1, and then I'll be working toward dnd5e 3.x, also.

**Comment by crash1115** [comment]
Yeah, I hopped into the discord last night to check out some of the conversation around 3.0. I think the priority you've set is fairly sane, and I have since settled on a similar stance. Gonna try to get things working with Tidy in 2.4.1 first, so there's a nice cutoff point for users who wanna use Tidy but don't wanna move to 3.0. Then I can shift gears. 

At the very least, the time spent on 3.0 updates helped give me a clearer idea of how exactly I wanna do this stuff, so it definitely wasn't time wasted.

**Comment by crash1115** [comment]
Pretty much done at this point, should have a release out by the weekend. Gonna give myself some time to do some more testing, but I think it's in good shape for anyone still using this version for whatever reason.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/41387713/2c80fcec-c284-4e28-8aec-41d2044efee2)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/41387713/e7495950-1827-4091-a97b-e696d8afeee2)

**Comment by kgar** [comment]
I'm really glad to hear that the API has been helpful! 
I have been working pretty nonstop on this for about 7-8 months. It's going to keep getting better if I can help it.

It really is a relief that the API docs are helping some. Adding tabs and tab content the conventional way was recently described to me as jackhammering, and I have to agree.

As far as styling goes, if you happened to use any Tidy CSS Variables, they are about to change back from namespace `--t5ek-` to `--t5e-` now that I've left alpha. That release is tonight.

**Comment by crash1115** [comment]
Awesome, thanks! Namespace adjusted, everything tested and released ([v1.0.3](https://github.com/crash1115/5e-training/releases/tag/v1.0.3)). We should be good to close this issue whenever! 👍

**Comment by crash1115** [comment]
Ah yes, the thing I forgot to test because I don't use it lol. 😅 Fix just went out in 1.0.4.

**Comment by kgar** [comment]
This was helpful for Tidy, because I needed a try/catch in that particular part of the integration code. It was inexplicably not in there yet.
Essentially, the sheet should still load even if the tab fails during any of its setup.
So I'll have a release related to this as well, haha.

**Comment by kgar** [comment]
Tested and confirmed.
Closing as completed. Woo hoo! 🎉
