### ISSUE TITLE
Advancement tab on Class Items doesnt support some filetypes

### ISSUE THREAD

**Issue by imivoltz** [kgar/foundry-vtt-tidy-5e-sheets#106]
When selecting a custom icon in the advancement tab in Class Items, only .svg files seems to display properly while different common file types like .png, .webp etc show some internal code on the file. I'll give a couple of examples of file types i've tested;

**.webp icons**

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/74024189/2ff93835-0dbb-495b-a981-90b993a3bbf5)

**.png icons**

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/74024189/e95180aa-d49d-4852-8471-5ac5183fb604)

**.svg icons**

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/74024189/6d2f8ce4-1b99-4b07-816e-de42d9884a06)

DnD5e supports .png and .webp file types by default and the latest version of Tidy5eSheet does aswell. 

**Dnd5e Base**

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/74024189/91cdc025-dd82-4422-adc6-203abb0fe09b)

**Latest Tidy5eSheet**

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/74024189/ffdfa9e3-fc42-41b6-94c5-f2d67582f749)

Foundry version: Version 11 Build 315
Dnd5e version: 2.4.0
Tidy5e version: 0.1.14

**Comment by kgar** [comment]
Top priority. Will fix as soon as possible and get a release out today if I can.

**Comment by imivoltz** [comment]
It is solved! A small sugestion on my part, would it be possible to hide the border of the image? Let me know if you want me to close this and open another issue for the sugestion 👍 

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/74024189/84e50e70-b720-41fc-b53a-ca5786dd7267)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/74024189/d610ed3c-2eed-4c98-8588-808a1b259ec8)

**Comment by kgar** [comment]
I will see what I can do

**Comment by kgar** [comment]
🤔, should be an easy fix.
Core Foundry style is doing it, apparently. I think the fix is for me to normalize my use of images to just not have a border in general, and if I need an image border, I'll intentionally add it to the CSS where appropriate. Will look into this more later.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/1d9e5eb6-b517-4cd3-8797-cd5ce3d5486e)

**Comment by kgar** [comment]
This is now released in [0.1.17](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v0.1.17)
