### ISSUE TITLE
Module Compatibility - Item Collection

### ISSUE THREAD

**Issue by KonteiKeisei** [kgar/foundry-vtt-tidy-5e-sheets#109]
https://foundryvtt.com/packages/itemcollection

This module works but has never had a tidy skin as it uses its own custom container skin.

**Comment by KonteiKeisei** [comment]
Also, right now a player has to edit the item to open the container, maybe a button to open separate from edit via right click? Ignore if not feasible or within compatibility scope!

**Comment by kgar** [comment]
> Also, right now a player has to edit the item to open the container, maybe a button to open separate from edit via right click? Ignore if not feasible or within compatibility scope!

With an API function and/or hook, custom icons / context menu options are possible, but 
1. I'll need to make the appropriate extension points in the code
2. the module will need to leverage the Tidy hook or function; I can supply a PR for such a thing to the module when I have made the appropriate prep on my end. 

So, this is definitely possible. It may take a little while. I have a few other module compat efforts in the queue. But you know me by now—I'll get there eventually.

**Comment by kgar** [comment]
Does dnd5e 3.0.0's new item container feature overlap with this? Or is this a different thing?

**Comment by kgar** [comment]
With the advent of container support and some of the inventory updates that I've got planned for Tidy, let's go ahead and let this one go.
