### ISSUE TITLE
Expand/Collapse List and Grid Sections

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#11]
For all actor types, wherever there is a list view or grid view, allow the user to expand and collapse individual item tables. Whatever their permissions, if the user can see the table, they should have the right to expand/collapse it.

- [x] Prototype it
- [x] Persist state to local session
- [x] Discuss visual indicators with the community
- [x] Add expand all / collapse all for a given tab; propagate throughout
    - [x] Actions tab
    - [x] Attributes tab
    - [x] Inventory tab  (list and grid)
    - [x] Spellbook tab (list and grid)
    - [x] Effects tab
    - [x] Abilities tab
    - [x] Cargo & Crew tab
- [x] Review the resulting HTML structure and apply polish
- [x] Review implementation and simplify as much as possible
    - [x] Consider consolidating the expandable/collapsible animation wrapper to a shareable component between item tables and accordions.

## Managing State

This should be stored on the sheet itself as a store and opted into via an interface implementation. Using tab/location context and some kind of unique identifier on the Item Table or Item Table Row Header, store expanded/collapsed state upon first change. When state is not available, assume the table is expanded.

Persist these preferences as part of sheet state in sessionStorage.

**Goals**: 
- Two separate users should be able to maintain their expanded/collapsed sections on the same sheet.
- Sheets should remember expanded/collapsed state so long as the browser tab remains unclosed.
- Stretch: Each tab should allow for expanding/collapsing all tabs.

## Stretch

For each tab where expand/collapse tables are supported, include Expand All / Collapse All controls.
(I'm not sure yet how to do this without adding clutter to the sheets)

## Reference

Discord discussion thread:
https://discord.com/channels/1167985253072257115/1189435918248058942

**Comment by p4535992** [comment]
The module https://github.com/tposney/dnd5e-scriptlets already to this https://github.com/tposney/dnd5e-scriptlets/blob/master/scripts/collapsibleActorSections.js, not sure if is compatible with Tidy, but can be a starting point for this feature integration.

**Comment by kgar** [comment]
I will definitely start there and look at the existing scriptlet.

**Comment by kgar** [comment]
> The module https://github.com/tposney/dnd5e-scriptlets already to this https://github.com/tposney/dnd5e-scriptlets/blob/master/scripts/collapsibleActorSections.js, not sure if is compatible with Tidy, but can be a starting point for this feature integration.

Was there a time when scriptlets used a caret or an arrow for the collapsible sections? I saw something like that on another person's Tidy sheets... Or has it always been the entire header row is clickable?

**Comment by kgar** [comment]
Prototype:

https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/eac8a78c-bd41-48b3-835b-67c0d2ebcddd

**Comment by kgar** [comment]
This update brings
- Expand/Collapse item tables
- Expand All / Collapse All
- A new utility toolbar with the controls rearranged for better use of the space

https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/9d784a0f-3217-48dc-9012-1952b54c4776

**Comment by kgar** [comment]
This has been released in beta 0.11.1.
It's been a long time coming.
