### ISSUE TITLE
formula for Ranger max spell prepared has typo

### ISSUE THREAD

**Issue by ctbritt** [kgar/foundry-vtt-tidy-5e-sheets#118]
should be `ceil(@classes.ranger.levels/2)+1` not `rangers`

**Comment by kgar** [comment]
Thanks for reporting! I'll have this in the next release.

**Comment by kgar** [comment]
Typo corrected in 0.1.18, just released: https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v0.1.18

**Comment by kgar** [comment]
Closing as completed
