### ISSUE TITLE
Rarity Colors not working

### ISSUE THREAD

**Issue by Dyrnwyrm** [kgar/foundry-vtt-tidy-5e-sheets#131]
Seems like the module inject the colors on the sheet so is not working, here is the module´s github

https://github.com/p4535992/foundryvtt-rarity-colors

**Comment by kgar** [comment]
Got the conversation started here: https://github.com/p4535992/foundryvtt-rarity-colors/issues/7

**Comment by kgar** [comment]
Rarity Colors is now compatible 💪
Closing as completed
