### ISSUE TITLE
Experience field is narrow

### ISSUE THREAD

**Issue by ZhornLegacy** [kgar/foundry-vtt-tidy-5e-sheets#157]
The space allotted for the the experience points "Current/Next Level" is a bit short.
At higher levels the values shown are clipped slightly as the field they are displayed in is not wide enough
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/106674701/c5662120-1624-45d4-ba7f-9357cba62367)

**Comment by kgar** [comment]
I will pursue a short-term fix of simply making it long enough for lvl 20. In the longer term, I'll seek out some approach that will scale the width based on XP to lvl up.
I should be able to get this in the next release, either today or tomorrow.

**Comment by kgar** [comment]
Accidentally closed the issue. The changes are in, and there should be a release tomorrow.

**Comment by kgar** [comment]
This is now released in v0.1.21. Have a look when able. Feel free to close the issue if it is resolved.

**Comment by ZhornLegacy** [comment]
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/106674701/1b44ac36-6e86-4a2c-831e-09eb978d2609)
Looks good
