### ISSUE TITLE
Compatibility with Trev33b's Dice-tooltip module

### ISSUE THREAD

**Issue by Opius134** [kgar/foundry-vtt-tidy-5e-sheets#166]
Just noting a quick request for compatibility with [Trev33b's Dice-Tooltips ](https://github.com/trev33b/dice-tooltip2) module. 

In the previous version of the tidysheet module, attacks and spells would show their roll data and damage types as so:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/8d903a95-37df-4712-9496-8a343272fc8d)

Currently, this functionality is missing:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/7f6b5ab1-dabd-4006-a181-bfc9247dad5e)

We do get a very brief popup? 
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/2fef589b-a836-4901-8ef2-ffe17abc3ca6)

Looks like that brief tooltip shows up with dice tooltips disabled as well. so it's not provided by that module at least.

I can't get any console information to spit out, unfortunately.  

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/c7df8e0b-131e-410a-b4ab-16a87e6391dc)
Latest foundry version, second to last dnd5e system module, running on Brave Browser (chromium), and self hosted. Let me know if more information is needed! 

Thanks for your work, and please consider this as a back-burner issue. It's super *not* game-necessary, just something I noticed when poking the mods list.

**Comment by kgar** [comment]
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/b672eaa6-84bd-41f6-8698-358bb436ae0d)

I'm wondering if we should call this one as Not Possible...

**Comment by kgar** [comment]
Hey @Opius134, I'm thinking we consider leaving this one behind. What are your thoughts?

**Comment by kgar** [comment]
I'm going to let this one go, since the module seems to have stagnated for over 2 years, and I can't get a response from the author.
