### ISSUE TITLE
[BUG] Items & Features cannot be rolled in newest update.

### ISSUE THREAD

**Issue by Zanderaf** [kgar/foundry-vtt-tidy-5e-sheets#176]
Updating to 0.1.22 is causing items to not be able to be rolled, in any way, not exactly sure whats causing it

**Comment by kgar** [comment]
A fix has been released for this. When able, have a look and feel free to close the issue if it is resolved.

**Comment by kgar** [comment]
Closing as completed. If you still have issues, let me know.
