### ISSUE TITLE
Calculate Max Prepared Spells?

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#20]
Is there a way to provide an option which calculates max prepared spells on the spellbook tab for player characters?
This calculation differs between spellcasting classes. How would we represent this difference?
Use a client / world setting or provide a max prepared spells formula box in the Class/Subclass item?

**Comment by p4535992** [comment]
A setting is not good for the individual actor, at the time I had used Sdenec's solution with the DAE module, but I think that giving the option on the actor's tab to enter a formula such as _"@classes.druid.levels + @abilities.wis.mod"_ (in a flag probably) should be sufficient for any use case, homebrew subclass or not.

**Comment by p4535992** [comment]
Add a piece of code as reference:
```
function calculateMaxPreparedSpells(ability, className, additionalBonus = 0) {
  const levels = actor.itemTypes.class.find(e => e.name === className)?.system.levels;
  const typeOfCaster = // add some code for this for say 2 == fullCaster, 1 == Half Caster, 0 === No Caster
  if(!levels) {
     return 0;
  }
  let maxPreparedSpells = 0;
  if(typeOfCaster == 2) {
     maxPreparedSpells = levels + Math.max(actor.system.abilities[ability].mod, 0) +additionalBonus; 
  } else if(typeOfCaster == 1) {
     maxPreparedSpells = (levels/2) + Math.max(actor.system.abilities[ability].mod, 0) + additionalBonus; 
  }
  return maxPreparedSpells;
}
const maxPreparedSpells = calculateMaxPreparedSpells("int", "Wizard");

```

**Comment by cs96and** [comment]
Don't forget that Artificers are like half casters, but have spell slots at character level 1.

Also, Eldritch Knights and Arcane Trickers (and possibly some other sub-classes that I'm forgetting) are quarter(?) casters.

**Comment by kgar** [comment]
Here's what I'm thinking...
The existing flag is fine to keep using, but we do this:
- Eval it like a formula when preparing to show it on the sheet
- Show the evaluated version as a readonly field in the UI and present a cog nearby
- Clicking the cog shows a little dialog with a formula input and some suggested formulae, based on the classes which I can legally mention there, using their documented formulas
- You can enter a formula in there, and we will evaluate it and show it on the sheet.
- When a character levels up, changes a relevant modifier, svelte knows what to do 💪

**Comment by kgar** [comment]
It also recalculates as your actor updates. So if you change Akra's wisdom or level up, it does exactly what is expected.

**Comment by kgar** [comment]
Coming soon,

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/7890edb7-57cd-4fdf-851f-2c13596c02ec)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/3ecf1d9b-362a-4342-a67a-6c56d84d2b7c)

**Comment by cs96and** [comment]
Excellent work.  What about Eldritch Knight and Arcane Tricksters?

**Comment by kgar** [comment]
> Excellent work.  What about Eldritch Knight and Arcane Tricksters?

If someone can supply me with a formula, I will add a button. I asked around on TPosney's server and got these, but I can definitely add more as I receive them.

**Comment by kgar** [comment]
> I found [this Google sheet](https://docs.google.com/spreadsheets/u/0/d/1UfZ9e9Z9XFiZ7uapyDxrh9UskZSmPGa-nWr7mCqzevw/htmlview#gid=0) that has lots of handy formulae. These are for Dice Cloud though, so a simple cut n paste might not work for foundry. The Eldritch Knight and Arcane Trickster spells known formulae are insane though.

They do look pretty complex. I wonder if those `if` statements work in Foundry's roll code. Thinking about this and various other edge cases, maybe I can provide an external link to a Tidy 5e sheet github repo readme with a fuller list of sample formulas 🤔

Especially because of all the subclasses out there and those that haven't been invented yet.

I can take user-submitted formulas, too.

**Comment by kgar** [comment]
Building it up here: https://github.com/kgar/foundry-vtt-tidy-5e-sheets/wiki/Max-Prepared-Spells-Formulas

**Comment by kgar** [comment]
Closing. Will handle any additional work in other issues.
