### ISSUE TITLE
Tabindex Refinements

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#21]
In the default 5e sheets and the previous edition of Tidy 5e sheets, one could tab from each of the text inputs. In this rewritten version of Tidy 5e sheets, there is a great deal more support for keyboard-driven sheet management, so more things can be tabbed to. However, this prevents the user from doing some very familiar tabbing, such as:
- Tabbing STR -> DEX -> CON -> INT -> WIS -> CHA inputs
- Tabbing from HP min to temp HP and temp HP Max

Evaluate what options there are to update tabindex and/or the keyboard support for fields such as Mod/Save rolls and config buttons so that these familiar tabbing paths are able to be used.

**Comment by voodoofrog** [comment]
Both the default 5e sheet and the prior incarnation of Tidy 5e sheet used the `type=hidden` attribute on the fields immediately surrounding the attribute inputs. I can't see a way to force the keyboard tabbing path to follow the same rules without basically doing the same thing. If you try to do it via `tabindex` you're going to have to set it for everything on the sheet, which is obviously a horrible idea and even then it will probably break the focus order for things _outside_ the sheet. Doing it programmatically will likely result in a similarly horrible outcome.

**Comment by kgar** [comment]
I agree. I let this issue sit while I worked on a lot of other stuff in the repo, and now that time has passed, I don't think it's worth the trouble, given the level of risk and/or churn it would require.

Ultimately, I would rather those buttons be available when tabbing through than require a mouse click.

I'm strongly considering a wontfix and closure on this issue.

**Comment by voodoofrog** [comment]
I'd say that's the safest bet if you wish to keep keyboard input available to the other controls.

**Comment by voodoofrog** [comment]
There is one other possibility, mind you, which would be to have it as an optional sheet setting toggle.

**Comment by voodoofrog** [comment]
I could work up a PR for that if you want?

**Comment by kgar** [comment]
Yeah, if you'd like to do one up.
I'm wondering where to put such an option. And should it be client- or world-scoped?

**Comment by voodoofrog** [comment]
I'd be inclined to keep it as client scoped as it's very much a user preference.

**Comment by kgar** [comment]
The fix for this is slated for the next release in 0-2 days.

**Comment by kgar** [comment]
Closing as completed with panache
