### ISSUE TITLE
Feature suggestion: Add a Hook for tab selection

### ISSUE THREAD

**Issue by Ikabodo** [kgar/foundry-vtt-tidy-5e-sheets#210]
If possible it would be nice to add a hook for tab selection. This way scripts can be run when a tab is selected and unselected.

What I'm looking to do is to run a short world script that renders the Paper Doll from https://foundryvtt.com/packages/fvtt-paper-doll-ui when the inventory tab is selected, then removed when another tab is selected.

**Comment by kgar** [comment]
Here's what I'm thinking:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/28afe411-aa23-4a15-9716-55993acfba03)

- tidy5e-sheet.preSelectTab 
    - can be cancelled like how preUseItem can be cancelled, by returning false
    - params
        - app
        - element 👈 this is an HTML Element, not jquery
        - { currentTab: string, newTab: string }
- tidy5e-sheet.selectTab 
    - occurs after the deed has been done
    - params
        - app
        - element
        - tab 👈 a string

**Comment by kgar** [comment]
This is ready to roll. When you get a chance, give it a shot. The API is as shown above.

**Comment by kgar** [comment]
Next step: Adding `tabSelected` call to the initial render of the tab strip.

**Comment by kgar** [comment]
The extra call to the tab selection hooks is now released in v0.2.4. I'm hoping to see the most rad paper doll appear on sheet open.

**Comment by kgar** [comment]
Closing as completed.
