### ISSUE TITLE
Tokenizer compatibility

### ISSUE THREAD

**Issue by Feuerhai** [kgar/foundry-vtt-tidy-5e-sheets#230]
Module allows creating custom tokens directly in Foundry.
[https://foundryvtt.com/packages/vtta-tokenizer/](url)
[https://github.com/MrPrimate/tokenizer](url)

Normally you can click on the character artwork on the character sheet to open up the tokenizer window, with shift-clicking allowing you to access the normal Image Browser. In the new sheet it just opens up the Image Browser on both a normal and shift click. (Was possible on the old sheet)

**Comment by kgar** [comment]
Thank you for reporting.
I have begun talks with the module author here: https://github.com/MrPrimate/tokenizer/issues/148

**Comment by kgar** [comment]
Beginning work on 
- `tidy5e-sheet.preOpenActorPortraitFilePicker` hook, to allow for cancelling the file picker open and doing something else, such as opening Tokenizer
- API for registering right-click actor portrait menu command buttons, so Tokenizer can opt to put a button on the right-click options

**Comment by kgar** [comment]
API support has been released for Tokenizer to add compatibility.
Now awaiting a release from Tokenizer module author.

**Comment by kgar** [comment]
Update on this:
MrPrimate has said he'll be able to get to the Tokenizer updates in a few days 🎉
He also just recently established compatibility between Tidy and DDB-Importer 🎉🎉🎉

**Comment by kgar** [comment]
Tokenizer is now compatible:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/d96dd062-15be-4847-855d-b5d81bcd7997)

From my testing, the functionality has moved to the portrait right-click menu:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/b45abded-3196-4c0a-8333-0203d76af2c9)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/57ca3987-28f1-4fc2-bcce-c60d716e8a0d)

**Comment by kgar** [comment]
Tested and closing as completed. If you have any issues, let me know.
Thanks for reporting the issue.
