### ISSUE TITLE
[Feature Request] Compatibility with TheRippers System Customizer. 

### ISSUE THREAD

**Issue by Orionox** [kgar/foundry-vtt-tidy-5e-sheets#235]
Currently compatibility seems to be pretty good except for the currencies, when the system customizer changes the currencies the character sheet doesn't update to match the new currencies.

**Comment by kgar** [comment]
It looks like the module requires purchase. I will contact TheRipper to inquire further.

**Comment by kgar** [comment]
Reference to troubleshooting with TheRipper: https://discord.com/channels/844900867240361984/1197054285679165500

Solution: Use `CONFIG.DND5E.currencies.${currency}.abbreviation` instead of `DND5E.CurrencyAbbr${currency}`

**Comment by kgar** [comment]
This has been released. When able, please give it a test and see if the issue is resolved for you.

**Comment by kgar** [comment]
Closing as completed.
