### ISSUE TITLE
Compatibility: Advanced Magic - Spell Points System 5e

### ISSUE THREAD

**Issue by Kharmans** [kgar/foundry-vtt-tidy-5e-sheets#247]
The module Advanced Magic - Spell Points System 5e adapts the Spell Points, but it doesn't work with this module.

**Comment by kgar** [comment]
I pulled down the module to test. I see some functionality works, such as setting a resource to "Spell Points" and having spell points get deducted when casting spells. Also, spell point recalculation on level up or class item drop seems to work.

Which specific functionality is not working?

**Comment by kgar** [comment]
This looks to be missing on my sheets:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/1dec8fa5-16a7-42d8-8b62-9a6d479cda58)

I can work with the module author on that.
Is there anything else in particular that doesn't work?

**Comment by Kharmans** [comment]
It's exactly the option "Enable Mixed Mode" that doesn't show. And if you don't use that option, the Spell Point are not automatically deducted when casting spells.

What I have to do is enable the "Enable Mixed Mode" option, change the sheet template to Foundry default, enable the Mixed Mode option and change to Tidy5eSheet template. That's the only way I can make the module works.

**Comment by kgar** [comment]
Gotcha. I am currently doing compatibility work for Magic Items 2, which is taking a lot of time, but when I get free to work on this, I will try to get it resolved. Much will depend on the module author, but as a backup plan, I can also provide a World Script to shim the functionality until the module author is able to update the module.

**Comment by kgar** [comment]
I've gotten the conversation with the module author started here: https://github.com/misthero/dnd5e-spellpoints/issues/63

**Comment by kgar** [comment]
The module author is planning to establish compatibility for this module and 5e - Custom Abilities & Skills 🎉

**Comment by Kharmans** [comment]
Thank you man! I'll wait.

**Comment by kgar** [comment]
@Kharmans from the module author, we are now compatible:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/462a8383-4047-4a6d-a438-d66c0ab79045)
https://github.com/misthero/dnd5e-spellpoints/issues/63#issuecomment-2114098159

Let me know if you need anything else. I'll give this issue a week or so, or until I hear back from you, whichever is sooner, and I'll close it.

**Comment by Kharmans** [comment]
@kgar, I just test it. It's working! Thanks for this!
