### ISSUE TITLE
[Compatibility Request] Simbul's Creature Aide

### ISSUE THREAD

**Issue by ZhornLegacy** [kgar/foundry-vtt-tidy-5e-sheets#248]
I would assume this is similar to resolving the legendary action functionality for Scriptlets
https://github.com/kgar/foundry-vtt-tidy-5e-sheets/issues/153

Essentially another request for the recharge mechanics to interact with the values on the character sheet.
Similarly to have features that use legendary actions to deduct from the remaining legendary actions field.

**Comment by kgar** [comment]
Thanks for reporting! 

Is it not currently working at all? Or are there particular parts of it that do work and don't work?

**Comment by ZhornLegacy** [comment]
Might be a false alarm caused by something else which has since been resolved?
At time of reporting legendary actions called per simbuls was not consuming their resource, nor where they being restored when the actors turn passed.
Current testing has it working.
Can no longer replicate issue.

**Comment by kgar** [comment]
This is the best kind of issue. 

If something comes up, feel free to reopen this one or make a new one.

Closing as completed.
