### ISSUE TITLE
[Compatability Request] Illandril's Inventory Sorter

### ISSUE THREAD

**Issue by kiligir** [kgar/foundry-vtt-tidy-5e-sheets#269]
Its GitHub page is here: https://github.com/illandril/FoundryVTT-inventory-sorter

The latest update to version 3.0.0 rolled forward a lot of libraries, and at least one of those borked compatibility with tidy. I have rolled back to 2.3.0, and it works just fine, so that's a temporary fix. It works fine on the normal sheet in its latest version. Low priority, since I'm more than fine just sticking at 2.3.0 until dnd5e or core Foundry completely borks it.

**Comment by illandril** [comment]
Version 3.1.0 of Illandril's Inventory Sorter is now compatible with Tidy 5e Sheets Kgar Alpha version 0.2.20

Since Kgar's sheets are still in alpha, there's a decent risk of changes here causing more incompatibility, but I'll be glad to investigate fixing any issues if you open an issue for it on my module's GitHub page.

**Comment by kgar** [comment]
Thank you @illandril!
If I can assist in any way, please let me know.

I will keep this issue open and in the "Waiting" status for when Tidy goes V1 and then dnd5e 3.0.0, just to be sure.

**Comment by kgar** [comment]
@kiligir can you determine if the module is working on Tidy beta 0.11.0?

**Comment by kgar** [comment]
@illandril now that the Tidy rewrite has officially taken over the package, the module ID is now "tidy5e-sheet". The "-kgar" suffix is now gone.

**Comment by kgar** [comment]
The compatibility code has been updated.
@kiligir do we need to keep this issue open any longer?

**Comment by kgar** [comment]
One more ping on this. I'll plan to retire the github issue after some more time.
