### ISSUE TITLE
Item Description "Popout" has no Background

### ISSUE THREAD

**Issue by Gensokian** [kgar/foundry-vtt-tidy-5e-sheets#276]
It might be due to incompatibility with other modules (There are a lot), but my Background of the box to the left of an Item or Spell has no background
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/9213561/0cfdfa43-e088-4064-8349-b6b3be300432)

I was able to hunt down the problem: The class "window-content" is missing in the div container.
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/9213561/958cdcc4-8ef8-4c6a-bc45-58e6295436c7)

**Comment by Gensokian** [comment]
Odd! Deactivating all addons seems to do nothing. But I think I found the culprit!
Checking the CSS it seems to use the background values of the variable `--t5ek-item-info-card-background`

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/9213561/fb3f7e26-03a9-40f9-8c29-32d8211d5b63)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/9213561/22bad6c8-6cfc-4db8-b36b-81f6134c8581)

Now this Value points to the "Relative" path `../../../ui/parchment.jpg` which on my end resolves to `https://dnd.MyDomain.com/ui/parchment.jpg` <- This does not exist.

Removing one of the path "back jumpers" (../) resolves the issue.
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/9213561/fb4abe73-b360-456c-ae0d-53ae2ca6f95f)


# Possible cause:
I am using docker for my foundry instance in which I have configured the `FOUNDRY_ROUTE_PREFIX` variable, basically adding a subpath to my domain, indicating what instance I am working on. Example: `https://dnd.MyDomain.com/v11/game` or `https://dnd.MyDomain.com/testing/game`.

**Comment by kgar** [comment]
This is good information. I'll see if I can recreate it. Either way, I'm hoping I can use a fallback style with the adjusted img path.

**Comment by kgar** [comment]
I am finally going to try to get Foundry into Docker for testing like this.
In the meantime, can you do an experiment for me with your setup?
Can you update the CSS variable for `--t5ek-item-info-card-background` to `url('/ui/parchment.jpg')`?

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/01940942-d98d-44c3-93db-5cda87675526)

**Comment by kgar** [comment]
I checked the rest of the URLs for this same issue, and it led to the discovery of missing checkbox checks in item sheets:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/fd8ad4cb-5c3c-460f-a95d-3b18c6e64df6)

That will be resolved in the update as well 👍

**Comment by kgar** [comment]
All right, New Tidy 0.2.17 has released with the fix for this. Please have a look at your earliest convenience.
Closing for now as completed, but if you run into issues, let me know, and we can reopen or add a new issue.
