### ISSUE TITLE
[BUG] Cannot edit spellslots (easily)

### ISSUE THREAD

**Issue by Gensokian** [kgar/foundry-vtt-tidy-5e-sheets#286]
Heya! Currently running a campaign with 1 person... Needless to say I require them to be able to adjust their spellslots. (Becuase 11 LV1 slots are fun right? Right.)

Now with the default sheet and non-alpha sheet there is this little pencil Icon where I am able to adjust the spell slots
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/9213561/50b60a22-35d2-4784-8f99-85e3c350816a)

In the alpha sheet, the "hit box" for this pencil is about 1 px as long as the sheet is not expanded further to the right.

Also, I am unable to deselect the field to save the value/stop editing it.
Thank you for your contribution upn one of the best 5e Charactersheets :)

**Comment by kgar** [comment]
Thanks for reporting! 🙏 
There is currently an issue out for dealing with the cramped item lists here: #14 

One of the goals for the spellbook tab is to hoist the spell slot pips and trackers above the list header row, as a special toolbar header of its own. Alternatively, we're also looking into the prospect of a left-hand spell slot / spell point summary area that gives a quicker look at the full spread of spellbook resources available.

After I get through the compatibility work and a few other features, I will be tackling this task. It's going to be a pretty big project, and I'll want to be careful and do by best to get it just right. So, I cannot deliver anything soon, but there *are* plans for resolving this.

**Comment by kgar** [comment]
Also, I was able to deselect and/or tab from the spell slot value/max fields from my testing.

**Comment by Gensokian** [comment]
> Also, I was able to deselect and/or tab from the spell slot value/max fields from my testing.
This is what happens when I try to select a field and then click sometime else. As you can see, it doesnt re-add the pencil.
https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/9213561/3d1040d4-1447-40b6-bc56-e6e5392b0ea2

**Comment by kgar** [comment]
The pencil is currently designed to re-add after a full close/re-open of the sheet.
It would be very odd if it were not allow you to click away from the input and unfocus from it.
Here is me clicking on an off the textbox after changing values.

https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/755dd5b6-3ffd-486e-8db9-fe35f38ce330

**Comment by kgar** [comment]
I value your time and effort to bring this up and to participate in other github issues on the repo, so I am going to honor that by figuring out a short-term solution to this problem. I will show you a prototype this week (hopefully).

**Comment by kgar** [comment]
In the discord Tidy server, we are floating various ideas. They are rough sketches and would need polish. They are conceptual layouts we could use to give breathing room to the content.

**Comment by kgar** [comment]
Here is one candidate layout option:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/c1a98207-0d61-4bbd-a74d-b062468dfc23)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/9da56c56-79a5-45c6-a095-8fdf3e3dfd40)

**Comment by kgar** [comment]
There were some strong opinions against adding more vertical space to the spell grid. As such I am renewing efforts to recover space as a standalone issue #293

**Comment by Gensokian** [comment]
Joined the discord and most likely will join some convos;
DIdnt have much time to mockup anything great, but Id have some Ideas to the spellslot problem, in case that helps:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/9213561/3e30d497-88a0-4a04-8eae-b0a5dfb95c7f)

Basically a manabar, vertical spellslots, stacked/blocked, and the horizontal manabar. Personally I love the horizontal Manabar, which could also contain the numbert of Slots or something.

**Comment by kgar** [comment]
We've recovered a little space in Tidy 2.7.0 by having the pips and value/max exclusive from each other. You can toggle them from the toolbar on the spellbook tab. 

I think future efforts are going to focused on a new eventual replacement spellbook tab that makes better use of the space than the current one, and column selection will seek to help with this sometime later. 

In any case, spell pips are going to better suited for smaller numbers of spells. 

Do you still want to keep the issue open?

**Comment by kgar** [comment]
More space has been recovered in 2.8.0 with the removal of the duplicate button and some trimming of excess space with columns.

Echoing the theme of the previous comment, pips are going to be best suited for smaller numbers of spells, and the Value/Max option will be more appropriate for larger numbers of spells.

**Comment by Gensokian** [comment]
Sorry for the long delay on the answer! I tested it a bit and honestly swapping between Numbers and Pips is the most optimal way of both ends, as people like pips and others like numbers. Beeing able to set about 32 spellslots without the sheet breaking probably is more than enough ^^

Thanks a lot for the awesome effort!

**Comment by kgar** [comment]
Thanks for taking part in Tidy's continued evolution. We have some good stuff on the way!
