### ISSUE TITLE
Incompatibility with 5eSheet-resourcesPlus

### ISSUE THREAD

**Issue by Opius134** [kgar/foundry-vtt-tidy-5e-sheets#30]
Currently the module doesn't play nicely with the [5e Sheet-Resources-Plus](**url**) module. 

Expected behavior:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/16c30649-b93e-4d43-8698-5da8bb45ec9b)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/85d0a515-360f-4a3a-8e9e-6e94ad871d20)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/d0034c34-c99f-4a7c-b0b2-d135cf814688)

This is on [sdenec](https://github.com/sdenec)'s branch. On the current Kgar's rebuild, it looks like this:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/e208b1b8-e833-4546-9932-040526c6e868)

Regardless of the sheet config's resource value (0-20) the sheet will display the _global_ maximum for the resources + module. 
Currently the bug shows no errors on the console, just the behavior on the sheet. 

Environment settings: 

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/4783779b-5bdc-49d9-9360-6c4f05980531)

Foundry Virtual Tabletop: Version 11 Stable, 11.313
Game System: dnd5e, 2.3.1
Active Modules: 5
Performance Mode: 0

OS: Windows 10
Client: Brave Browser [Version 1.60.110 Chromium: 119.0.6045.105 (Official Build) (64-bit)
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 (0x00002487) Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

**Comment by kgar** [comment]
After an initial review, I think this will require some collaboration on my part with the module developer.

I'm putting some notes here also for future me so I can refer back to them:

For the short term, these are the two problems:
- The new character sheet has a different constructor name: "Tidy5eCharacterSheet"
- The new character sheet resource blocks have scoped styles, so their classes need to be preserved when the module dev is applying a "hidden" class.

In the long term, using an API-driven approach will ensure that this feature can work with other sheet layouts in the coming year(s) without the need for more patches and churn.

I think a short term fix during alpha testing is probably going to be fine, and we can worry about the long term fix later. I can submit a PR to the target repo soon.

**Comment by kgar** [comment]
Release 0.1.16 has the necessary compatibility changes on Tidy's side:
https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v0.1.16

Awaiting pull request results from the integrating module: https://github.com/ardittristan/5eSheet-resourcesPlus/pull/36

A world script is available for anyone who wishes to have compatibility sooner: https://github.com/kgar/foundry-vtt-tidy-5e-sheets/blob/main/compatibility/world-scripts/5esheet-resourcesPlus.js

Realistically, if everything looks good, let's give the module author some time to respond. If you test with the world script and find something is different than it would be in the default sheets, go ahead and post that here.

**Comment by kgar** [comment]
The author has just yesterday published a release with my changes and some changes of their own within it. When able, give the latest version of the module a test and see if it is working as expected, without a world script.

**Comment by kgar** [comment]
I did some testing. It looks like there's an error occurring before we get to the compatibility sheet wiring up part: https://github.com/ardittristan/5eSheet-resourcesPlus/issues/37

I will test again after this is resolved.

**Comment by kgar** [comment]
Because of the dnd5e 3.0.0 situation, it's time to leave this one behind.
In 3.0.0, Tidy will be providing a way to add a varying number of resources that are not just favorites.
Closing as completed with the "World Script" level of compatibility.
