### ISSUE TITLE
Alternating colors for Traits/Skills

### ISSUE THREAD

**Issue by PwQt** [kgar/foundry-vtt-tidy-5e-sheets#303]
Whenever you hide non-proficient skills/traits for NPCs, the "alternation" of colors for that table disappears, it appears like the colors are just hardcoded to the elements.

![obraz](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/12457218/8984b01e-e588-4a54-ab7f-2a8071a27b84)
![obraz](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/12457218/cfa4381e-94bc-46c8-860f-63818a43be23)

**Comment by kgar** [comment]
I did a recent change that hides instead of removes the rows, which made it way more performance. I need to update the CSS to stripe only the visible ones, now.

**Comment by kgar** [comment]
As it turns out, the `nth-child()` selector will count all children, visible or not, regardless of what selectors you use 🥴
Fortunately, there is a sibling combinator approach that can work here.

```html
<div class="row">Hello</div>
<div class="row hidden">Hello</div>
<div class="row">Hello</div>
<div class="row">Hello</div>
<div class="row">Hello</div>
<div class="row">Hello</div>
<div class="row">Hello</div>

<style>
  .row { background: orange; }
  .row:nth-child(even) { background: green; }
  .row.hidden { display: none; }
  .row.hidden ~ .row:nth-child(odd) { background: green; }
  .row.hidden ~ .row:nth-child(even) { background: orange; }
</style>
```

**Comment by kgar** [comment]
I've done some more experimenting and analysis,...

For now, I will revert the show/hide logic back to include/exclude logic.

For module devs who want to inject stuff directly into these areas of the sheet, I cannot compute/hardcode row striping, so include/exclude will have to be the way until CSS catches up with this use case.

**Comment by kgar** [comment]
Changes are merged in and awaiting release.

**Comment by kgar** [comment]
This has been released. Closing as completed.
