### ISSUE TITLE
bug: "system.attributes.spellcasting" defaults to "Intelligence" if set to "None"

### ISSUE THREAD

**Issue by DevConFox** [kgar/foundry-vtt-tidy-5e-sheets#331]
When trying to set the spellcasting ability to "None", the selection defaults to "Intelligence" for both "PC" and "NPC" actors.
If the sheet is set to Foundry default and the ability is then set to "None" the value is correctly set.
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/93077838/537e09db-8d9b-4758-881d-caae263f50de)

**Comment by kgar** [comment]
Thanks for reporting. I'll have the fix in the next release.

**Comment by kgar** [comment]
This has been released in v0.11.3.
Closing as completed.
