### ISSUE TITLE
Feature Labels

### ISSUE THREAD

**Issue by Kharmans** [kgar/foundry-vtt-tidy-5e-sheets#336]
When use Feature Types and Subtypes, their names can be too much long. I think would be better if the Subtype was bellow the Feature, like in the original sheet.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/112586547/4d0f9433-9563-47fe-84f5-f12222196332)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/112586547/b653c557-d885-4fed-a1e1-b3f7432796e2)

**Comment by kgar** [comment]
Agreed. When able, I'll get this adjustment added. Probably after dnd5e 3.x compatibility is established.

**Comment by kgar** [comment]
Sorry for the wait. The adjustment is coming out in tomorrow's release.

**Comment by kgar** [comment]
Closing as completed. See the updated item sheets in Tidy 3.1.0
