### ISSUE TITLE
The module no longer appears

### ISSUE THREAD

**Issue by Melkyor** [kgar/foundry-vtt-tidy-5e-sheets#338]
Good morning,

Since this evening, I have noticed that the Tidy 5e sheet module no longer appears at all in my list of modules.
An uninstallation-reinstallation does not solve the problem.

I'm on Foundry VTT 10.291 and DnD5e 2.2.2, hosted on The Forge

Thank you in advance for your answer.
Sincerely

**Comment by kgar** [comment]
The last supported Tidy 5e Sheet version for Dnd5e 2.2.2 can be installed using this manifest URL:
https://github.com/sdenec/tidy5e-sheet/releases/download/0.9.19/module.json

I have not used Forge yet, but I believe you can install this version using the "Install from Manifest" button:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/cf667348-7e76-4bdd-8c58-4f602f337d7b)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/40e79ce1-714d-4e2c-ba71-18c1f50c1fa1)

Also, Tidy 5e Sheets version 1 is soon to be released for dnd5e 2.4.x, and after that, I am preparing it for dnd5e 3.x and Foundry V11+.

**Comment by kgar** [comment]
Reposting from discord:

## Tidy 5e Sheets Version 2.0.0-beta.1 Released 

Github release: <https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v2.0.0-beta.1>
module.json: <https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/download/v2.0.0-beta.1/module.json>

**:rotating_light: For dnd5e 3.0.x :rotating_light:**

## The Tidy Open Beta for dnd5e 3.x is Here :dragon:

The URL-only open beta for Tidy 5e Sheets support in dnd5e 3x has begun. There are a number of things to polish, and there are whole features to implement from scratch (such as containers and hiding unidentified item content). There are migrations to make (dnd5e 3.x now has Age, Eyes, Skin, etc.; so Tidy will be retiring its own version of those fields).

I will be aggregating a full list of features and planned updates in this milestone as the days go by: <https://github.com/kgar/foundry-vtt-tidy-5e-sheets/milestone/3>

The goal of this beta is for dnd5e 3.x users, or those who have been ready to go to 3.x, to be able to try out the sheets in the latest dnd5e system version. I will be addressing any issues that arise and can/will release additional beta pre-releases. In the background, while I wait, I will be working down those milestone feature rollouts.

As always if you are jumping to a new version of dnd5e, **don't forget to backup your world**.

Feel free to file issues if something isn't quite right when compared to the legacy sheets. I request you mention `dnd5e 3.0.x` in the title, such as `bug: (dnd5e 3.0.x) Vehicles Fail to Polymorph into Liches`.

Cheers, everyone.

### Forge Users: This Release Might Show Up in Your Options

If you are using Forge, you might see the v2.0.0-beta.1 version appear in your options. I have not published an official package for v2 Tidy to Foundry, so this may come from some other factor. Be advised that Tidy v2.0.0-beta.1 is for dnd5e 3. If you accidentally update Tidy, you can safely downgrade back to v1.x Tidy.

**Comment by MsVella** [comment]
I am also getting this issue too, the module is not showing up in game when i try to enable it, however the modules list says it's installed.

**Comment by MsVella** [comment]
Update: Installing from manifest URL did work properly. I noticed this issue because when i updated the module dissipated (was no longer enabled and stopped working) from my world

**Comment by kgar** [comment]
To help me troubleshoot, can you tell me
- Foundry Version
- dnd5e system version
- Tidy 5e Sheets version
- Are you using Forge? Are you installing via Forge?

Can you take some screenshots of the installation screen and the modules list when logged into the Foundry world?

Is the web console showing any errors?

**Comment by kgar** [comment]
@Melkyor were you able to perform a URL-only installation?
@MsVella are you all set, now?

**Comment by Melkyor** [comment]
> @Melkyor were you able to perform a URL-only installation?

Hi,
In the meantime, I updated Foundry VTT to version 11 (patch 13 - build 315) and also that for DnD 5e 3.0.3.
The Tidy 5e sheet module now works again but... the new character sheets in the DND system are really beautiful and work quite well!
In these conditions, I will put Tidy aside for the moment.

In any case, thank you for your responsiveness and for the work you have accomplished.

**Comment by kgar** [comment]
Glad to hear things are working again. Enjoy the new default sheets! They are working on new NPC sheets in 3.1, too.
Closing as completed.
