### ISSUE TITLE
Items on Journal tab don't render

### ISSUE THREAD

**Issue by dstein766** [kgar/foundry-vtt-tidy-5e-sheets#35]
IF the Journal tab is a core function of Tidy (I assume it is, but if being added by another module I've completely forgotten that), then tidy-kgar isn't rendering any of the data.  My test PC has data in both the Journal Entries and Miscellaneous fields.  Screencaps show missing Journal Entries - I didn't bother to screencap evidence of missing Miscellaneous.  I assume Persons of Interest, Locations of Interest, and Quests would also render blank although I didn't test.

Tidy (original);
![lQl4hL1pqq](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/24942951/55fcd032-37d4-4e90-87a6-b75a6b525703)

Tidy-kgar:
![pgxbcw69qC](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/24942951/b31de405-b4c4-44d7-b919-82162cca9f84)

**Comment by kgar** [comment]
Are you able to set some journal text from the alpha sheet and see it render properly?

**Comment by dstein766** [comment]
OK - makes sense.  (The specific answer to your question is that, as expected based on your explanation, new text entered in tidy-kgar DOES render under tidy-kgar (but not under tidy-original) and vice versa.   Closing this issue since this is not a bug.

**Comment by kgar** [comment]
Good to hear, and my apologies for any confusion. 

When this project moves to beta testing, I can look into using current Tidy's actual data flags to make the final transition to v1 a smooth process. Right now, the changes are bigger and more disruptive, so I hesitate to commit to that yet.

Thank you for trying it out.
