### ISSUE TITLE
Compatability with modules that add new tabs

### ISSUE THREAD

**Issue by Ikabodo** [kgar/foundry-vtt-tidy-5e-sheets#37]
First of all, thanks for putting some love to these sheets. I can already sense the improvement (mostly in speed!)

A thought though. Several modules such as "Crash Tracking and Training", "Downtime", "Ethck's Downtime Tracking" and "Beaver's Crafting Module" all add tabs to the sheet.

These are currently not rendered on your sheet. I assume they simply don't hook on to your sheet?

**Comment by kgar** [comment]
Hello, thank you for checking out the rewritten sheets!

With the rewrite, a lot of things are very different under the hood from regular Foundry sheets. This will have broken compatibility with numerous sheet-augmenting modules. When these sheets leave alpha testing and move on to beta, module compatibility changes will begin in earnest.

I will refer back to this issue to see what can be done.

**Comment by Ikabodo** [comment]
I think this change you are doing is really good for this.

One problem with the above modules is that they add tabs on sheet update hooks. That can be very performance heavy. With your solution tabs can be added at the core (at least that is what I think it looks like).

Nice work!

**Comment by kgar** [comment]
Thank you. Beta is coming soon, and I'll be putting all my energy into this problem.

I am hoping I can get in touch with some of the module devs to collaborate on how the API should look and feel. I will be reading through those modules to see how they're currently being done and maybe even submit my own PRs after I have API coverage available for the kinds of functionality they are providing.

When compatibility is restored, their tabs should appear in places like Initial Sheet Tab, Default Tab Selection, and Actor Tab Selection, like first class citizens 🤞

**Comment by kgar** [comment]
I have started some github discussions on how to provide module compatibility for new tabs.
I will be awaiting and participating in any discussion on the topic for another couple of weeks.
https://github.com/kgar/foundry-vtt-tidy-5e-sheets/discussions/93

When I reach the end of that period, I'll begin work on the API and will target one module at a time until the overwhelming majority of use cases are covered.

**Comment by kgar** [comment]
Let's go... Downtime Dnd5e is now compatible!
Crash's module may not be feasible, since Downtime Dnd5e is the spiritual successor, but I will discuss it with Crash.
I've submitted an issue to Ethck's Downtime Tracking to get the conversation started.
I'll be getting the conversation started with Beaver's Crafting soon.

**Comment by kgar** [comment]
Beaver's Crafting is in!
Hoping to hear from Ethck sometime soon.

**Comment by kgar** [comment]
Ethck has begun the work to add compatibility 🎉
I helped with testing, and I provided some feedback. It is now Ethck's move.

**Comment by kgar** [comment]
Crash recently said he was working on tab registration.
Ethck started a branch as well and has basically completed the work.
With dnd5e 3.0.0 on the way, that might slow things down quite a lot.

However, I now have numerous tools for module authors to use when adding tabs.
Should we close this issue and track any specific modules separately?

**Comment by kgar** [comment]
Closing as completed. I'll consider this github issue to represent the task of providing API tools. 
Now tracking the specific tab-adding modules in their own issues.
