### ISSUE TITLE
feat: (dnd5e 3.x) Effects Search and Filtering

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#370]
dnd5e 3.x brought search to the Effects tab. Does Tidy want to do the same?

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/86e80906-c7bf-4487-ad6a-2648c44fabf2)

**Comment by A1exanderWebb** [comment]
Just some random guy here, not really a mid/dnd5e power user, but I personally would not likely get much use out of a search filter for effects. I can't think of any actors I have that have more than 15 or so effects at an absolute maximum, and as long as they are split between passive, temporary, and inactive, I have no trouble parsing the effects quickly by eye.

**Comment by kgar** [comment]
This is a great point and something I've heard said before when discussing with others before dnd5e 3.x dropped.
And, having room for conditions on the effects tab is going to be pretty vital, so real estate on that screen is pretty precious.

**Comment by kgar** [comment]
Closing as unplanned. If there is enough of a community interest in this, we'll come back to it and do something.
