### ISSUE TITLE
Max prepared spell formulae for Bard and Sorcerer

### ISSUE THREAD

**Issue by cs96and** [kgar/foundry-vtt-tidy-5e-sheets#379]
I've managed to come up with some Max Prepared Spell formulae for Bard and Sorcerer.  They are not prepared casters, so they calculate the correct number of Spells Known instead.

Sorry but the formulas are pretty horrendous...

### Bard
`max(@classes.bard.levels + 3, (min(floor(@classes.bard.levels/10),1) * (14 + min(floor(@classes.bard.levels/11),1) + min(floor(@classes.bard.levels/13),1) + (min(floor(@classes.bard.levels/14),1) * 2) + min(floor(@classes.bard.levels/15),1) + min(floor(@classes.bard.levels/17),1) + (min(floor(@classes.bard.levels/18),1) * 2))))`

### Sorcerer
`min(@classes.sorcerer.levels + 1, 12 + min(floor(@classes.sorcerer.levels/13),1) + min(floor(@classes.sorcerer.levels/15),1) + min(floor(@classes.sorcerer.levels/17),1))`

**Comment by kgar** [comment]
Nice! I'll add those buttons to the dialog.
Later, I'll look into a feature to allow toggling the wording so it's not always "Prepared spells".

**Comment by kgar** [comment]
With the Bard formula, it looks like the Bard ends up with 23 spells known instead of 22 at level 20. This makes sense when reading the first section of the max() function:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/e5fe4087-a5ba-41de-bb60-acdfcba56ee6)

**Comment by kgar** [comment]
I'll have this ready to merge into main for Tidy 1.x and then out to beta Tidy 2.x.
If you happen to find a way to fix the bard formula, I'll listen for that here.
If a solution is not possible, we can still put this formula out there, as it will still help people a lot. All the other levels are exactly right.

**Comment by kgar** [comment]
Masterfully done. I'll get these formulae into the mix with this next release. Thank you!

**Comment by kgar** [comment]
The new formulae are live. Thanks a ton for these!
