### ISSUE TITLE
Feature request: Add filter for Activation cost "Other"

### ISSUE THREAD

**Issue by cs96and** [kgar/foundry-vtt-tidy-5e-sheets#380]
It would be handy if there was a filter for an Activation Cost of "Other".  This would be any item/spell that is not an action, bonus action or reaction.

The main use case for me would be for filtering out longer casting spells (e.g. 1 minute) for NPCs when in combat.

**Comment by kgar** [comment]
I was also considering adding filters for the other activation costs, depending on the what the community thinks. With that in mind, I'm wondering if there's a name for this filter that would still capture the idea of "Not Action, Bonus Action, or Reaction" if the other activation cost filters were also present.

**Comment by kgar** [comment]
I gave it some additional thought.
"Other" is probably best for now. I think it's more useful to add this filter now and worry about the other activation costs later, if at all.

**Comment by kgar** [comment]
It has been released to all tracks. Thanks for making Tidy better!
