### ISSUE TITLE
[Feature Request] Temporary Tidy 5E NPC Sheet only mode for DnD5E 3.x

### ISSUE THREAD

**Issue by SirAron111** [kgar/foundry-vtt-tidy-5e-sheets#398]
Is there a way to get a Temporary Tidy 5E NPC Sheet only mode for DnD5E 3.x give that the full rewrite for player character sheets will take a while, having to deal with the default npcs sheets as a DM, so my Players can enjoy the new sheet of 3.X is a pain. Is there a way to get tidy working just for the npcs or so currently it's not enableable at all due to low version stuffs.

**Comment by kgar** [comment]
I have a URL-only beta available for dnd5e 3.x, but the official update is coming in a few days.

Copied from the community discord:

## Tidy 5e Sheets Version 2.0.0-beta.4 Released 

Github release: <https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v2.0.0-beta.4>
module.json: <https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/download/v2.0.0-beta.4/module.json>
Planned features progress: <https://github.com/kgar/foundry-vtt-tidy-5e-sheets/milestone/3>

**🚨 For dnd5e 3.0.x, URL-Installation-Only beta 🚨**

## What's New?

See [v1.3.0 release notes](<https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v1.3.0>)

## Saying Goodbye to 2.4.x Soon...

In just a few days, Tidy 5e Sheets development will shift entirely to dnd5e 3.0.x development, and the first official Tidy v2 package will be released.
On the Foundry package page for Tidy 5e Sheets, I keep a table of the last Tidy version for each dnd5e system version where there are breaking changes.
<https://foundryvtt.com/packages/tidy5e-sheet>
See "Legacy dnd5e System Compatibility"

**Comment by kgar** [comment]
Tidy V2 is live. I will close this as completed, but feel free to report any issues, should something come up.
