### ISSUE TITLE
When "allow cantrip preparing" setting is enabled - allow "prepared" filter to exclude unprepared cantrips

### ISSUE THREAD

**Issue by TrofimSelbs** [kgar/foundry-vtt-tidy-5e-sheets#405]
Hey, love the module. If it is possible, could you please implement an enchancement, which allows to declutter spell list by removing unprepared cantrips with filter? Thank you

![SCR-20240224-tzct](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/124184162/a99d2006-e0ca-4dba-80a2-9e51b980d1be)

**Comment by kgar** [comment]
Tidy v2.7.0 now have this feature. Give it a try and see what you think.

**Comment by kgar** [comment]
Closing as completed.
