### ISSUE TITLE
Ability to roll death saves does not show for players, only shows for DM

### ISSUE THREAD

**Issue by DrDucksauce** [kgar/foundry-vtt-tidy-5e-sheets#406]

**Comment by kgar** [comment]
Is this a feature request, a bug report, or other?

**Comment by kgar** [comment]
Have a look at #414. Would that work for you?

**Comment by kgar** [comment]
I have not heard anything back from you about this for quite some time. Can you check your settings to see if "Hide Death Saves" option is turned on?

If I do not hear back, I will eventually close the issue as unplanned.
