### ISSUE TITLE
Icons from web adresses invisible

### ISSUE THREAD

**Issue by Feuerhai** [kgar/foundry-vtt-tidy-5e-sheets#43]
If you have an item/feature with an icon that is not locally on the server and instead points to a web adress, the icon is not shown on the sheet and instead just shows an empty box. It works on the default sheet and the old tidy sheet.
![no icon](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/25032400/562a8ed0-1e1a-4a5c-ba50-fac6c6ba2fe2)

**Comment by kgar** [comment]
Check out the v0.1.4 update and close this issue if it looks good to you.

**Comment by Feuerhai** [comment]
Now only icons from web adresses show and non of the local ones

**Comment by Feuerhai** [comment]
Works after the next update

**Comment by kgar** [comment]
For anyone else who sees this in the future, the svelte dev server environment interprets URLs from a CSS variable differently than a prod build. The dev server was interpreting `--bg-image` relative to the top-level web URL, whereas regular functioning from the website results in relative URLs being scoped to the location of the file, i.e., the module folder, resulting in a 404.
