### ISSUE TITLE
bug: weight in Inventory undefinied

### ISSUE THREAD

**Issue by McMuffin88** [kgar/foundry-vtt-tidy-5e-sheets#463]
![Screenshot 2024-03-09 144732](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/75749644/fe59a1fe-76bf-467f-a510-63c79284a584)

Pictures say more than words :)

I have tried to deinstall the Module and clean reinstall - but dont work.
Maybe i am not the only one who have the Problem?

**Comment by Niclasp1501** [comment]
I have the same issue. The weight is "undefined". I am using v11 315 and D&D in version 3.0.4. 
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/44606632/6840d66c-74c9-453f-ad97-b7b043372693)

**Comment by kgar** [comment]
Thanks for reporting. I'll look into this as soon as possible.

**Comment by kgar** [comment]
I am not seeing this issue, even when adding new items:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/b87133bf-7349-4e65-a854-948fa099e9ed)

Can you share the exported actor JSON where this is happening, so I can better diagnose the issue?

**Comment by McMuffin88** [comment]
Hi, 

here my JSON

[fvtt-Actor-test-alex-ONfK3seHTG6j4sO6.json](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/files/14546955/fvtt-Actor-test-alex-ONfK3seHTG6j4sO6.json)


Hope it helps to diangnose the Issue.

**Comment by Niclasp1501** [comment]
Attached is the JSON of one of my players. The issue also occurs with newly created players. I have disabled all modules to check if there are any problems caused by other modules. If there is any other way I can assist you in troubleshooting, please let me know. Thank you very much for your work.
[fvtt-Actor-brom-nigrestes-kijXeY4hqF4nlSy4.json](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/files/14546971/fvtt-Actor-brom-nigrestes-kijXeY4hqF4nlSy4.json)

**Comment by kgar** [comment]
I wonder if it could be because of weight unit, perhaps?
Here is what I see when importing an affected actor:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/dd897d8a-01f4-4f33-9f9c-4cd8c17dfdbe)

**Comment by kgar** [comment]
No luck when I switch to the metric system:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/33e409ca-79c3-4f50-9593-3355cf5835a6)


Do you have any non-default Tidy, Core, and/or dnd5e settings that I can try to apply?
Do you have any world scripts that change anything?

**Comment by kgar** [comment]
I am using dnd5e 3.0.4, Foundry 11.315, and Tidy 2.5.1.

**Comment by kgar** [comment]
Got it!

I set the language to Deutsch and can see it now

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/f07358b5-f059-4c87-aa92-551f0513af28)

I'll begin working on a fix now and will follow up when it is ready.

**Comment by kgar** [comment]
Someone submitted fixes to the German translation, and I have released those in Tidy 2.5.2.
Please give it a try and let me know if things are good or still bad. I am still reviewing the localization files for any more issues like this one.

**Comment by kgar** [comment]
After my review, I found additional places in the German language file where things needed correction.
I have released Tidy 2.5.3 with additional fixes.
When you are able, get latest and let me know if the issue is resolved.

**Comment by Niclasp1501** [comment]
@kgar  
With version 2.5.3, it is now working again. Thank you very much. I was just trying out 2.5.2 and about to write to you that it wasn't working when I saw your message about the release of version 2.5.3. Tried it out, and it worked immediately.
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/44606632/f0ede571-289a-4aa1-ba8d-5d3e379d0a29)

**Comment by Niclasp1501** [comment]
@kgar Can I give you a small tip somewhere?

**Comment by kgar** [comment]
I'm glad to hear it is working again. I accept translations from the community, and sometimes a translation error may occur. I will try to be more vigilant when reviewing submitted translations. This was the first time I'd seen this particular mistake happen.

Thanks for trying out the sheets! If you'd like to support the project, I have support links here: https://github.com/kgar/foundry-vtt-tidy-5e-sheets?tab=readme-ov-file#how-to-support

**Comment by McMuffin88** [comment]
Works fine. Thank you
