### ISSUE TITLE
bug: Rarity Colors of Inventory

### ISSUE THREAD

**Issue by AzureCamel** [kgar/foundry-vtt-tidy-5e-sheets#468]
I'm really enjoying the Tidy Sheets module update, and I thank you for maintaining it. After the recent update, I noticed the Rarity Colors module integration that changes item colors in the inventory isn't working as it used to. Could you please take a look? Thank you so much once again.

https://github.com/p4535992/foundryvtt-rarity-colors

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/98294508/7970cc9c-d9a4-4900-b767-98ce2e0f29d9)

**Comment by p4535992** [comment]
I think that is the old tidy sheet can you post the modules versions  both tidu and rarirty colors?

**Comment by AzureCamel** [comment]
Yeah, I can do that. I'm not sure what version it stopped working for me as well.

Tidysheet - 2.5.3 
Rarity Colors - 0.3.14
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/98294508/a682b720-7f11-410e-bed9-f5f0bdc0962c)

**Comment by kgar** [comment]
Sorry for the wait. I've submitted a pull request to Rarity Colors with the compatibility fix: https://github.com/p4535992/foundryvtt-rarity-colors/pull/15

**Comment by AzureCamel** [comment]
Thank you very much, I used your version and it works great. Thank you again for the work you've done maintaining Tidy Sheets. The sheets feel better than ever!
