### ISSUE TITLE
style/theme: Threat Color Theming and Capacity/Encumbrance Threat coloring

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#470]
Rename
- --t5e-warning-accent-color 👉 --t5e-threat-color
- --t5e-warning-accent-contrast-color 👉 --t5e-threat-contrast-color

Utilize these colors for threatening situatons:
- Encumbrance exceeded
- Capacity exceeded
- Attunement exceeded (sun icon and arcane overflow effect)

Pair this upgrade with #207

**Comment by p4535992** [comment]
If you want to integrate this feature I would ask you (if it is not too much work you mean) for some hooks or api to be able to synchronize the Variant Encumbrance module with the configurations chosen by Tidy. Linked to this ticket  https://github.com/kgar/foundry-vtt-tidy-5e-sheets/issues/250

**Comment by kgar** [comment]
Sure thing. I will keep this front of mind while working on this feature.
It should amount to CSS variables in the end.

Once I get free from my current feature upgrades, I will return full attention to module compatibility and get currency and encumbrance adjusted to play nice with modules.

**Comment by kgar** [comment]
I'm going to let this one go. The visual overhaul will be a fresh start, and we can go from there.
