### ISSUE TITLE
Dark Theme: Item text headings unreadable

### ISSUE THREAD

**Issue by ZeroXNoxus** [kgar/foundry-vtt-tidy-5e-sheets#492]
When Dark Theme is enabled and I try to view items or features with headings (in this case html h3) they are unreadable as they have a grey-ish color:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/29397572/7557ff98-5020-4269-9da8-3ec17fb1e15e)

**Comment by ZeroXNoxus** [comment]
This styling could solve this issue quiet nicely:
`.tidy5e-sheet:where(.actor) .item-summary h1, .tidy5e-sheet:where(.actor) .item-summary h2, .tidy5e-sheet:where(.actor) .item-summary h3, .tidy5e-sheet:where(.actor) .item-summary h4 {
    color: #ffa400;
}`

**Comment by kgar** [comment]
Are those header styles coming from the SRD compendium content? Or are they imported from somewhere else?

When I use headers in Tidy with the dark theme enabled, I get this style:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/95ee6fd8-d570-4769-8ec4-66b6567b0f5b)

**Comment by 9ryex5** [comment]
> When Dark Theme is enabled and I try to view items or features with headings (in this case html h3) they are unreadable as they have a grey-ish color:
> 
> ![image](https://private-user-images.githubusercontent.com/29397572/313139842-7557ff98-5020-4269-9da8-3ec17fb1e15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDU0MzIsIm5iZiI6MTcxMTEwNTEzMiwicGF0aCI6Ii8yOTM5NzU3Mi8zMTMxMzk4NDItNzU1N2ZmOTgtNTAyMC00MjY5LTlkYTgtM2VjMTdmYjFlMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEwNTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNTA4NGI5M2NkZGZlZWI4YjRjNjYyYzFiMDFkYjBlZTE2NTliMzA1Yjc3OWZkYmEyOWMwMGUzOTE1ODBhMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hy2Kmr5-4CE9fIUFB3wt5hNG7dmNqXwxbVwnXmGPnGM)

This header is probably copied from somewhere else and comes with formatting. 
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/43207603/f4f6c954-a79f-4082-af7c-44af956ce6fb)
Clear formatting and it will display nicely like kgar's screenshot.

**Comment by kgar** [comment]
Is there anything else we should discuss on this issue?
