### ISSUE TITLE
compatibility: Midi-QoL Actor On Use Macro

### ISSUE THREAD

**Issue by MythicalRollers** [kgar/foundry-vtt-tidy-5e-sheets#505]
I am just starting to move to dnd 3.0+ Midi's Actor on use Macro section does not show up.  Default 3.0 character sheet, it does.  Legacy, it does.  Tidy, it does not.  Please allow for this to be visible again at your earliest convenience.
Can verify this with only Midi, Tidy5e, and required modules on.
Foundry: 11.315
DND5e: 3.0.4
Tidy5e: 2.8.0

**Comment by kgar** [comment]
Hello, thanks for reporting!

This is something that Midi QoL specifically puts onto the sheets. The sheets themselves are not adding this UI.
I submitted an issue to Midi QoL a few weeks ago with the necessary code to incorporate the Actor On Use menu to Tidy's traits section. It is still open at this time: https://gitlab.com/tposney/midi-qol/-/issues/1368

I recommend adding a comment to the gitlab issue to put it front of mind for the module author.

We can keep this github issue open as a means of keeping track of that effort.

**Comment by kgar** [comment]
I pinged TPosney to check up on this. I'll let you know what I find out.

**Comment by kgar** [comment]
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/60a44924-dd24-49ac-a0a8-c755ce8bbd0d)

**Comment by kgar** [comment]
Midi QoL 11.4.16 now includes "Actor On Use Macros" config in Tidy 5e Sheets:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/c8f000fd-1b75-4852-baa2-29b92dc0b17a)
