### ISSUE TITLE
[FEATURE] TidySheet for Scene configuration 

### ISSUE THREAD

**Issue by ZeroXNoxus** [kgar/foundry-vtt-tidy-5e-sheets#519]
Would it be possible to include a sheet for sceen configuration? 

And thanks already for the hard work!

**Comment by kgar** [comment]
If I were to do it, it would be quite a while later. I'm still catching up with dnd5e 3.0.x and now 3.1.x additions for Character / NPC / Vehicle sheets. I also am planning to do Group Sheets.

Any idea what we might improve upon, aside from CSS styles? Any pain points with Scene Configuration where a different approach would help?

**Comment by ZeroXNoxus** [comment]
I completely understand this and hope the new 5th Edition changes aren't too bothersome.

Not too much to be honest. But one thing comes to mind; Inputable Sliders (eg. Darkness Level, Global Illumination Threshhold, Padding Percentage, etc.). A number field to manually input values would be really nice.

**Comment by kgar** [comment]
With Foundry overhauling these application windows, I'm more inclined to let this effort go. The actor and item sheets take so much time all their own.

**Comment by kgar** [comment]
I just finished a major code migration for the existing Tidy sheets, and I realize there's a lot of files and code in there now, after a year and a half of working on the sheets. I don't think I can add many more sheets to the roster and still maintain everything at a decent level of quality. So I can't take on this task.
