### ISSUE TITLE
COMPATIBILITY: Fix Module 'So Inspired!' Compatibility With New TidySheet V3

### ISSUE THREAD

**Issue by GameCrazed** [kgar/foundry-vtt-tidy-5e-sheets#538]
Following the discussion with Kgar & That Guy.. in the feature-ideas channel, can the So Inspired! module be brought back up to date with the V3 tidy sheet please? Currently if the module is enabled and the inspiration cap set to any number > 1, it removes the inspiration icon entirely (see image below).

Foundry: 11.315
DND5e: 3.1.1
Tidy5e: 3.1.0
So Inspired!: 0.2.1

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/7393464/d0fbbb97-f3f0-431c-b0e8-14da282f6757)

**Comment by kgar** [comment]
I just now took a look.
It is removing the Tidy Inspiration tracker, but it is attempting to put the new tracking somewhere on the Legacy Sheet's structure, and therefore, it is not placing it successfully.

**Comment by kgar** [comment]
When I align Tidy and So-Inspired, this is what I get:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/820c23bb-36e2-400c-8cdb-c611eecd4b97)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/3b96e60c-1297-4563-8822-c191e0027042)

**Comment by kgar** [comment]
Module repo: https://github.com/mysurvive/so-inspired

**Comment by kgar** [comment]
Cross-post: https://github.com/mysurvive/so-inspired/issues/1

I am now awaiting the module author's response.

**Comment by kgar** [comment]
The module author is cool with it. I've submitted a PR for their review.
There may be Tidy Bennies in your future, yet!

**Comment by GameCrazed** [comment]
Woo! Thank you again ^_^

**Comment by kgar** [comment]
The module have been updated. Get latest and give it a test run.

**Comment by kgar** [comment]
Closing as completed.
