### ISSUE TITLE
Add compatibility for ItemMacro

### ISSUE THREAD

**Issue by BlackBadger777** [kgar/foundry-vtt-tidy-5e-sheets#54]
For now, ItemMacro can't be used with the new Tidy5e Sheets. The macros stored in ItemMacro won't trigger when the character sheet uses the Alpha sheets.

**Comment by kgar** [comment]
Now I will go ahead and evaluate what needs to be done to get this working again.

**Comment by kgar** [comment]
🎉 The latest Tidy 5e Sheets and the latest Item Macro now work together. 🎉
At your earliest convenience, have a look and see if it is working as you'd expect.

**Comment by kgar** [comment]
Closing as completed.
