### ISSUE TITLE
[Bug] DnD 5E base PC Sheet not changeable to tidy sheet if it was set to the default one manually before.

### ISSUE THREAD

**Issue by SirAron111** [kgar/foundry-vtt-tidy-5e-sheets#540]
DnD 5E base PC Sheet not changeable to tidy sheet if it was set to the default one manually before.
I have noticed that since the last few updates, one of my players sheets can't be changed to the tidy sheet anymore.
While out of my 5 players, 4 used Tidy, so I set the tidy sheet to be the default sheet.
This meant that the one player who preferred the new base dnd sheet, I set theirs to the default one in the "this sheet" setting.

But since editing the sheets is actually easier in tidy for me when I fix stuff or do things out of session, I normally switch her sheet back to tidy, but that isn't working since the last two updates.
When I set the "this sheet" settings to tidy or default which is tidy, it seems to reload the sheet but just stays on the default one and ignores the setting.

Could it be that some bug fix or change that happened since then is causing the sheet and default sheet thingy to be ignored if it was previously manually set to something else than the sheet set to default?

**Comment by kgar** [comment]
The other user experiencing this issue believes it to be caused by "Monk's Enhanced Journal". Can you check your modules and see if you have this module and whether disabling it temporarily causes the issue to go away?
They also report that it's only affecting Character sheets and not the others.

**Comment by Trekari** [comment]
Experiencing the same issue here. Disabling MEJ immediately allowed me to switch the test PC back to Tidy Sheets.

This is after today's update, btw. Without disabling MEJ, even the new update does not fix the issue.

**Comment by kgar** [comment]
That user on the Tidy discord is messaging ironmonk to see if something can be done about it 🤞
I will keep the issue open as a Compatibility ticket so others can see this paper trail, until the issue is fully resolved.

**Comment by SirAron111** [comment]
ye its a compat issue with monks or so it seems.

**Comment by kgar** [comment]
@SirAron111 it seems IronMonk has released a fix to this issue. Can you verify that things are resolved on your side?
I'll keep the issue open for a week or so, or until I hear back from you, whichever is sooner.

**Comment by SirAron111** [comment]
Yep its fixed
