### ISSUE TITLE
[BUG] Attack roll bonus on item sheets disappears

### ISSUE THREAD

**Issue by Aspencrown** [kgar/foundry-vtt-tidy-5e-sheets#544]
Hello there!

So, I noticed this when I was shoring up my compendiums and tweaking a weapon I had made a bit ago. Like the title says, whenever I tried to add an attack roll modifier to the weapon, it immediately disappeared. Then I tried to do the same on other weapons on PC sheets -- same problem. I checked the console log and found no errors.

After turning off all mods, I did not have the issue in question. Curiously though, whatever number I entered that previously disappeared was there.

Turned on my mods again and then I rolled on the weapon I was trying to fix and even though no modifier was visible on the sheet, it did end up rolling with the +2 that it's supposed to have.

I then fired up Find the Culprit, went down the list, and it said that Tidy Sheets was the cause of the problem. I then went to check I had the current version, found that I didn't, but an update did not fix it either.

Thanks in advance for taking a look at this and for all that you do.

**Comment by kgar** [comment]
Can you show me a screenshot of the part of the item sheet you're talking about?
And then a screenshot of where it has gone missing?

**Comment by kgar** [comment]
This was likely a change in the data model when moving to dnd5e 3.0.x or to 3.1.x.
Either way, I should have the fix good to go for the next Tidy release.
Thanks for reporting!

**Comment by kgar** [comment]
This is now released in Tidy 3.2.0.
