### ISSUE TITLE
Some font sizes are smaller than the original Tidy 5e sheets

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#55]
https://discord.com/channels/1167985253072257115/1170003836556017755/1175748614878937178

BlackBadger777 — Today at 4:45 AM
Is it just on my end, or is the font in the new sheets even smaller than in original Tidy5e? 
On the left is the default sheet, middle is original Tidy5e, right is the new Alpha. I must admit, the font is getting pretty small for my old eyes 👴

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/db2a4816-3493-41cc-a6ab-00827d78b8fa)

**Comment by kgar** [comment]
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/0f4fc37a-c617-4100-92ab-4ca96c2fe429)

Determined the font sizes to be the same with Tidy 5e Alpha 0.1.8 / Tidy 5e Original 0.9.18 on Chrome Version 119.0.6045.160 (Official Build) (64-bit), Windows 10 Version 10.0.19045 Build 19045

The user who reported the issue is going to verify their alpha sheets version and follow up later.

**Comment by BlackBadger777** [comment]
After some more follow-up and trouble-shooting, it turned out that clearing the cache of the browser (Edge, in this case) fixed the issue.
