### ISSUE TITLE
feat: Pf2e-Style Inline Containers

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#560]
Implement inline containers in the PC / NPC / Vehicle / Container sheets in the style of Pathfinder 2e, curated for Tidy 5e Sheets:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/b48e998e-9c00-4d5e-941c-da5191e4056e)

## Notes

The following features would be nice to include:
- Container Capacity bar
- Recursive containers; allow the user to drill down to containers within containers. The UI cannot accommodate nesting to extreme levels, and it will not try to, but in general, users should be able to dig several levels within
- Open/Close button next to the item name
- Be able to expand/collapse item description as well
- Drag and drop within a container sorts
- Drag from outside a container and drop into a container should transfer the item to the container with the appropriate sort applied, whether it came from the main inventory or another container, related or not
- Drag from inside a container and drop to the main inventory should unpack the item into the main inventory and assign to its default / configured section
- Classic controls for container items should match the controls of the Container Contents table
- Container Contents tab should feature the same capabilities for expanding containers
- (TBD) Show containers in search results when any of the descendants match search criteria
- (TBD) Provide a way to open a container and all descendant containers in one action
- See (and edit) currency at a glance in the inline container content area

**Comment by kgar** [comment]
Paging @crash1115 in case you'd like to weigh in on this during planning

**Comment by DanielTheBard** [comment]
Would also love if there could be a way to see the coins in a container at a glance, as well (without just editing the item).

**Comment by kgar** [comment]
@DanielTheBard the beta release for this feature is now live: https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v4.0.0-beta.5

Note: I've been working with the community to find a Tidy way to show currency in the inline containers, but we haven't found it yet. If we cannot come up with something before beta testing is over, I will make a standalone github issue for it.

**Comment by kgar** [comment]
Beta testing is nearly complete. We'll make currency UI a separate goal so there's more time to ponder it.

**Comment by kgar** [comment]
At long last, it is done.

The github issue is only a few months old, but this has been something we've wanted since well before containers came out in dnd5e.

Hardly time to celebrate this win, but I am still very happy to have been able to make this update.

Closing as completed.
