### ISSUE TITLE
Extra tooltip appears when hovering over an item/spell

### ISSUE THREAD

**Issue by SilvesTheRog** [kgar/foundry-vtt-tidy-5e-sheets#562]
Hello!
I've noticed that when hovering over an item, spell, ability etc. etc. there's a tooltip with its name under the cursor. The thing is, it sometimes overlaps the information card (if it's enabled to appear near the cursor) or some other UI elements. Sometimes it works fine. For example, hovering over DEX it shows Dexterity in the tooltip, but there are places where it's completely unnecessary. I believe there is no need to duplicate the item's or ability's name when I'm already looking at it with the cursor placed there. 

Would be great if there was a way to disable/configure this tooltip. 

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/127493227/7d7ed670-5a62-493c-807e-411204f0f730)

This tooltip is "exclusive" too Tidy 5E. It does not appear on default 3.0 character sheets or legacy ones:

![Screenshot 2024-04-10 183928](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/127493227/70277046-8295-400b-8655-8f5ef9acdde9)
![Screenshot 2024-04-10 183942](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/127493227/2646d54b-c920-4eb3-8926-76953a023c19)

I am using the latest FVTT stable build, D&D 5E system and Tidy 5E sheets. Also tested with disabling all the other modules, except for Tidy 5E

**Comment by kgar** [comment]
Thank you for reporting this. It will take a little longer to overhaul the tooltips here because of ongoing projects, but I will make sure that the Item Name tooltip does not pop up when the item card is in floating mode.

The tooltip exists to ensure that even the item name, when truncated with ellipses (...), will still tell the player the item name. I can definitely see how that would be irrelevant when using floating item cards.

**Comment by kgar** [comment]
My apologies for the wait. I am going to remove the small tooltip from the item/spell names. There are other things which have small tooltips, like the classic control icons, and those will stay.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/151b31d7-90e0-4309-b4f4-1dc608e035d3)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/1096e737-ec3b-4f1c-8f22-1f3d19669fbe)

Will this work for you?

**Comment by kgar** [comment]
This is now released in Tidy v4.3.0.
