### ISSUE TITLE
Text added to Item HTML tab does not save

### ISSUE THREAD

**Issue by BillPitcher** [kgar/foundry-vtt-tidy-5e-sheets#563]
Make an Item (Loot), in any of the Description options click the edit button.
Click the HTML "/"
Paste in HTML
Click Save
It's gone, no text. Switch to the Default 5e Sheet do the same and it's saved.

**Comment by kgar** [comment]
Thanks for reporting. I'll look into this.

**Comment by kgar** [comment]
Thank you again for taking the time to report this issue and to help improve this module. 
The latest Tidy 5e Sheets release now contains the fix.
https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v3.3.1
