### ISSUE TITLE
Add option to customize what tabs are displayed

### ISSUE THREAD

**Issue by crash1115** [kgar/foundry-vtt-tidy-5e-sheets#57]
(If this is already a thing, I am super sorry. Currently out of town and haven't had a chance to check out the alpha yet.)

Description of Feature: Add a way to customize which tabs are displayed in the sheet's navbar. Adding a "Customize Tabs" option to the sheet's customization menu that brings up a list of tabs with checkboxes would probably suffice. Whenever functionality is added to the sheet API that allows external modules to add tabs to the sheet, it'd be nice if those additions also showed up as options here.

Use Cases: I can think of a few off the top of my head, and I think this solution for them falls firmly inside the scope of a sheet module like this (especially one to make the sheets... tidier):
- I'm playing a fighter and don't need a spellbook tab.
- A group keeps session notes and descriptions of characters in an external program and doesn't need the bio or journal tabs.

**Comment by kgar** [comment]
I had not made an issue for it yet, but this perfectly describes the tab selection feature I'd also envisioned. In terms of priority, I have two other upgrades planned during alpha, but I'd like to include this one in that short list. Thanks for posting!

**Comment by kgar** [comment]
Check it out:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/9928421c-587f-4b92-9f5a-b83d2bb9f345)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/ead1eee3-5ea2-4628-95d1-22fb8b02248b)

Next is to provide some UI for setting that flag 💪

**Comment by kgar** [comment]
Where to find it:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/ee5c039b-206e-4f90-b384-2ed0b06230f3)

**Comment by kgar** [comment]
I'm using a selection listbox:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/0155a5cb-c2be-40d0-aada-28305ba7835f)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/e1fd3d48-1de1-4958-823c-d17161d241f9)

Ideally, I'd like to also support drag-and-drop to sort and to transfer.

**Comment by kgar** [comment]
I'll be writing up a release later tonight. There are some things that I have chosen not to deal with at the moment (the Sheet Lock looks weird when you select only one tab in tab selection).
When the release goes out, feel free to test-drive it. Depending on feedback, I may do some additional changes as part of this github issue or request a new issue so that it can be prioritized. If everything looks good, let me know here on the issue and feel free to close it.

**Comment by kgar** [comment]
All right, 0.1.10 is here, and it includes tab selection for this issue.

**Comment by crash1115** [comment]
Yoooo, this is very cool! I love being able reorder the tabs. My group has definitely argued about whether it makes more sense for Spellbook to come before or after Features before, lol. Problem solved.

Is there implementation for 3rd party mods to add tabs in this version or nah?

**Comment by kgar** [comment]
Yes. SooooOOOooon.

Module compatibility is coming soon. I have an API (work in progress) for adding tabs, and all tabs added through the API by other modules will show up in the tab list. It's all connected 🤌

I am nearing the end of alpha testing, and then this repo goes beta, all my energy (except for any bugfixes) will go to building the API and getting most of the critical modules compatible.

**Comment by kgar** [comment]
Also released just today: you can set the default for each actor type in Sheet Settings. Check out the latest release notes for more details.

**Comment by kgar** [comment]
Closing this one. Enjoy! 
If you have any issues or questions, feel free to add an issue.
