### ISSUE TITLE
Macro issues.

### ISSUE THREAD

**Issue by MythicalRollers** [kgar/foundry-vtt-tidy-5e-sheets#583]
When using some of Crymic's macros I get the following error with TidySheet.

Error: Error thrown in hooked function '' for hook 'tidy5e-sheet.actorPreUseItem'

Also, thank you for your time and staying on top of my other "issue" about midi and actor on use.

**Comment by kgar** [comment]
I think this is related to the Item Macro module. I'll see if I can get with the module author to help out with that.

**Comment by MythicalRollers** [comment]
Oh! I'll try it with Midi's DIME and see if I get the same error.

**Comment by MythicalRollers** [comment]
Using MIDI's DIME negates this. I guess maybe Item Macro is obsolete for MIDI users.

**Comment by kgar** [comment]
I'm going to go ahead and close this issue after a few more days.
I've submitted a fix to the Item Macro module: https://github.com/Foundry-Workshop/Item-Macro/pull/16
