### ISSUE TITLE
[BUG] Item cards don't' support Cyrillic letters in price

### ISSUE THREAD

**Issue by TrofimSelbs** [kgar/foundry-vtt-tidy-5e-sheets#587]
Hey! Love the module. Noticed that there is an issue, when the coin names are in Cyrillics - they are not displayed. you can see on the photo below that they are not visible in blue area. Would be great if you could fix this! Thank you

![SCR-20240517-lsmq](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/124184162/c99703df-b15e-40bf-b5b4-1cf95a9a4f73)
![SCR-20240517-lsgc](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/124184162/c30b5dea-6251-4ddb-b607-ad77ef67c5dd)

**Comment by TrofimSelbs** [comment]
Addinional info: I used "find culprit" and found out that tidy sheets was causing this, but I am maybe wrong

**Comment by kgar** [comment]
Thanks for reporting. I'll see if I can get that fixed.

**Comment by TrofimSelbs** [comment]
Thank you for looking into this!

**Comment by kgar** [comment]
Question for you: How do I use this language in Foundry?

**Comment by TrofimSelbs** [comment]
Sorry, I am a bit confused about what you mean. If you are asking how can you set this language - you can in Foundry settings change English to Russian. Cyrillic is a name of the alphabet, like latin for English, but Cyrillic for Russian and a few other languages

**Comment by kgar** [comment]
I tried to find the Russian language in options but could not. I will look again.

**Comment by TrofimSelbs** [comment]
Not sure if this is the official website but it is listed [here](https://foundryvtt.wiki/en/languages) I have it in my settings but I am not sure that I have it without a module.There is a [module](https://foundryvtt.com/packages/ru-ru) that makes Russian better (it was turned off while testing for this issue though). Not sure if this helps

**Comment by kgar** [comment]
I installed the Russian translation and left it turned off, and I checked on my desktop computer instead of my laptop. Now I see Russian as an option. I'll get on this.

**Comment by kgar** [comment]
With Russian set as the preferred language, I see:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/b47ae789-0579-4444-aba5-2401d9f2a5b3)

I am using 
Tidy 5e Sheets v3.3.3
Foundry v11.315

Active Modules:
- Tidy 5e Sheets

**Comment by TrofimSelbs** [comment]
hey, sorry for the long anwser. 
1) Thank you for giving Babele and Russian translation modules a try. They are the ones that I use as well
2) I have Custom 5e and Item piles, which both have currency settings. I believe only the former modifies world anything. However, to verify, that that is not those two that are causing this issue - I have run a Find Culprit and still had this issue. It looks like, in your screenshots, you are having it too. I do have prices in the dropdown menu, but if I set them and then add the item to the charachter sheet - the price doesn't show up.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/124184162/b512f824-effa-42a0-9c4a-11b3fe282d47)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/124184162/9dce5460-ad43-4844-a59a-0b522f5d8e6a)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/124184162/e6a7f7ef-ec7b-4ea8-9bb2-edc15d841401)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/124184162/b0b60ed2-c34f-4f91-85bb-faed5ac8023f)

Now I go into the dropdown menu and change currency to GP. It remembers that it is GP and it will stay this way. However, from this there are 2 issues:
1) If I use Tidy sheet for my items - I can't see price in the compendiums
2) If this player transfers the item to another player, who uses new 5e sheet, instead of Tidy 5e sheet - they can't see the price.
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/124184162/70bb0928-fc6b-4d08-82d5-eba03b3593ad)

**Comment by kgar** [comment]
Thank you for the details. It gives me a clue about what Tidy might be doing. I think this info is enough to help me figure it out.

**Comment by TrofimSelbs** [comment]
Great! That is awesome. Thank you for your attention to this issue

**Comment by kgar** [comment]
Try out Tidy v3.4.2 when you are able.
I believe I found the issue, thanks to your troubleshooting.

**Comment by TrofimSelbs** [comment]
yes, it is working! great thank you, kgar!

**Comment by kgar** [comment]
Glad to help. Thank you for finding a bug. This will help many other users with other languages enabled.
