### ISSUE TITLE
Adjust how multiclass spell dropdowns are populated

### ISSUE THREAD

**Issue by crash1115** [kgar/foundry-vtt-tidy-5e-sheets#59]
This includes:
- PC Sheet > Spellbook tab > Filter dropdown
- Item Sheet > Details tab > Spell Class dropdown

I think the ability to distinguish spells based on class is extremely useful, but I never used this feature in old Tidy. Mostly because it felt very clunky to me. Having the dropdown filled with options for every possible class makes using them cumbersome and confusing. Populating the dropdowns based on classes the actor actually has would probably make more sense. If I'm a Ranger/Druid, I don't need to see Wizard and Artificer on these lists.

I'm not sure how often you're getting access to things from classes you don't have, so I don't see use cases for the current implementation, but I could very well be missing something. If that's the case, then an alternative could be to keep the dropdown in the item sheet as is, and limit the one on the spellbook tab to classes that actually have spells assigned to them. So if I'm a Ranger and assign one spell to Cleric and one spell to Sorcerer, the options would be Cleric and Sorcerer.

**Comment by kgar** [comment]
Coming to Tidy V5.1.0, spellclass filter and new Source Class option on the spell sheet details tab:

![image](https://github.com/user-attachments/assets/6db61c2f-9a32-4c26-8b5c-466fe15ed353)

![image](https://github.com/user-attachments/assets/c949c2a7-1610-4d24-9138-02d7072606e8)

This is just a start, but I point it out so we can start thinking of how to refine it further and make it less clunky.

**Comment by kgar** [comment]
issue in question: #671
