### ISSUE TITLE
Sheet scrollbar present when no scrolling needed if using Firefox

### ISSUE THREAD

**Issue by M0nk3yy** [kgar/foundry-vtt-tidy-5e-sheets#61]
When logging in via Firefox, the scrollbar does not disappear even when the sheet window is enlarged to the point where there is no scrolling to do.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/66137312/988de00c-7fe8-4ee4-a9ca-beef99af449a)

It is also somewhat wider compared to the scrollbar that legacy Tidy5e uses in Firefox. (Though still not as a slim as the Chrome one).

**Comment by kgar** [comment]
I've released a fix for this. If everything looks good to you, go ahead and close the issue.
