### ISSUE TITLE
NPC Initiative Sheet Button

### ISSUE THREAD

**Issue by Ehill05** [kgar/foundry-vtt-tidy-5e-sheets#610]
Is there anyway a feature could be added to allow for rolling NPC initiative without tokens on the map, the way you can for PCs?  This would be a really useful feature for games in person using Foundry as a map on a screen that could have built-in initiative tracking too.

**Comment by kgar** [comment]
I tested it out just now with a monster from the SRD compendium, and it seems to work.

I have canvas disabled, and I opened the monster from the sidebar.
Then, I started an encounter and clicked to roll initiative.
It added the monster to the tracker.
I did it a second time to see another copy of the monster get added to initiative.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/1de51ee1-cbe0-44da-8f91-cd8c38f7ba6a)

**Comment by kgar** [comment]
This was with Foundry V12, Tidy 4.0.0-beta.2, but I would expect it to work on Foundry V11 with Tidy V3.5.0 also.

**Comment by Ehill05** [comment]
I'm running v12 and didn't realize I needed the beta, you just solved my problem!  Thanks!
________________________________

**Comment by kgar** [comment]
I'm glad to hear it. Happy gaming!
