### ISSUE TITLE
Bug: Clicking on Spell Pips Does Nothing [4.0.0-beta-2]

### ISSUE THREAD

**Issue by crash1115** [kgar/foundry-vtt-tidy-5e-sheets#611]
When I click on spell pips to adjust the current number of spell slots on a PC or NPC sheet, nothing happens; the current value doesn't update, there's no errors in the console, and the little animation doesn't play. This is true in both the Spellbook tab and the Attributes tab (favorites) for PCs.

Running...
- Foundry v12 (build 324)
- dnd5e v3.2.0
- Tidy 4.0.0-beta-2
- No other modules

**Comment by kgar** [comment]
Hey, thank you for catching that! I'll get this fix in today's beta release.

**Comment by crash1115** [comment]
Working great in 4.0.0-beta-3 👍
