### ISSUE TITLE
bug: Errors when changing equipment Action Type to Enchant [4.0.0-beta.3]

### ISSUE THREAD

**Issue by crash1115** [kgar/foundry-vtt-tidy-5e-sheets#615]
**What's Happening?**
When I set the action type of an item to Enchant, a lot of things go horribly wrong. The update doesn't seem to take (dropdown doesn't update, and the sheet doesn't re-render), and I get the first of the attached errors in console. Furthermore, when I close the item edit window and reopen it, nothing displays in the Details tab at all and I get the second set of errors. This also happens on existing items, not just freshly created ones.

At one point I did this and nothing rendered in any of the tabs on the actor's sheet, and another time I couldn't switch between tabs on the actor's sheet. I couldn't reliably reproduce either of those issues, but they happened about half the time.

**Steps to Reproduce**
- Open up a character sheet
- Go to the Inventory tab
- Create a new item (I used Equipment and Weapon in my testing)
- Edit the item, go to Details Tab
- Set the Action Type to Enchant

**Environment Info**
- Foundry 324
- dnd5e 3.2.0
- Tidy 4.0.0-beta-3
- No other modules

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/41387713/d0b9ac6b-7052-4f17-86a4-36ab8a1e72c2)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/41387713/9d9cee31-e5ac-4687-8926-2d63406c58fa)

**Comment by kgar** [comment]
Good catch. I've got the fix inbound as soon as I release the next beta. Setting that up now

**Comment by kgar** [comment]
Beta 4 is out with the fix.

**Comment by kgar** [comment]
Tidy v4 is here with all the fixes from beta testing. Closing as completed.
