### ISSUE TITLE
Resources cog gives overlaid text for recovery

### ISSUE THREAD

**Issue by M0nk3yy** [kgar/foundry-vtt-tidy-5e-sheets#62]
Hovering resources cog gives mixed up overlaid text:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/66137312/6144ff5b-99b5-47f9-9394-0d936b65ab3b)

Repro'd in FLC and Firefox.

**Comment by kgar** [comment]
Probably the cleanest / low-risk way for me to solve this is, ironically, with the `:has()` CSS selector, but Firefox has bumped out-of-the-box support for this selector to the December 19 release of Firefox 121.

#42 is awaiting the same feature in Firefox.

I'll get a PR started with the ideal fix, and then I'll see if I can find a workaround for the short term.

**Comment by M0nk3yy** [comment]
No worries, Dec 19 is short term!

**Comment by kgar** [comment]
I've release a fix for this. If everything looks good to you, go ahead and close the issue.
I'll plan to remove the temporary i-cannot-`:has()` stuff as part of issue #42 and retest this in firefox.
