### ISSUE TITLE
Error with spell attack modifier on the spellbook page (4.0.1, DnD3.2.0, V11)

### ISSUE THREAD

**Issue by Opius134** [kgar/foundry-vtt-tidy-5e-sheets#624]
Encountering a bug affecting Tidy 4.0.1 when running on DnD5e 3.2.0 in Foundry 11 build 315.

When a character has an effect that modifies msak or rsak, the console throws and error and the spellbook page fails to calculate the modifier. 
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/4d0f8c17-1e7e-47d4-896b-8380d99e916d)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/852ecb8c-4194-4667-9572-c40d36004982)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/9b66a2f7-ee57-4af7-80b6-4720841fc7e6)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/334235f1-d347-454d-b87d-70671cc78dec)

The odd part is, dice rolls seem to work correctly, and the Actions page appears to show the correct modifiers. 
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/100728089/8b8caf45-e855-4f48-80b0-9c39b4273066)

I looked about and saw this issue appeared elsewhere in previous editions, and Midi and DAE seem to be involved in these cases. In this instance, I'm running on DAE 11.3.28 and Midi 11.4.33. 

Not sure if this is a bug or a configuration issue on my part.

**Comment by kgar** [comment]
I'll see about getting this fix deployed in a few hours.
