### ISSUE TITLE
New NPCs have no default Creature Type

### ISSUE THREAD

**Issue by M0nk3yy** [kgar/foundry-vtt-tidy-5e-sheets#63]
This results in the inability to click the Creature Type in order to select one.

Usage in existing Beast type NPC:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/66137312/18892447-d8fb-4f48-a06b-66ecc3bb333b)

Blank space on new NPC:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/66137312/0a5a5ee7-7675-4597-8b81-7b33a4f62907)

Expected experience using legacy Tidy5e:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/66137312/6b6a5b9d-7cb4-432f-b4e2-57ebbba516bf)

It is similarly not possible to assign them a source in the new "Source" field.

**Comment by kgar** [comment]
I've release a fix for this. If everything looks good to you, go ahead and close the issue.
