### ISSUE TITLE
Bug: Cannot delete items from sidebar containers using right-click menu

### ISSUE THREAD

**Issue by TheSquishyDitto** [kgar/foundry-vtt-tidy-5e-sheets#631]
When using the Tidy 5e Container Sheet with 'Use Classic List Controls' disabled, attempting to delete an item from a container by using the right-click context menu throws an error and does not delete the item. This only seems to occur with containers in the Items sidebar—containers within Actor sheets work as expected.

**FoundryVTT Version 11 Stable - Build 315**
**System:** D&D 5e 3.2.0

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/8783856/bc603aa9-1cc1-45fb-b866-77e784ad431e)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/8783856/1a2faf7d-1d6b-4a53-a48a-9216f4ac2950)

**Comment by kgar** [comment]
Thanks for reporting! I'll have the fix in the next release.

**Comment by kgar** [comment]
Tidy v4.1.1 has fix 🔧
