### ISSUE TITLE
Compatibility: Tidy 5e x Steinhardts Guide to Eldritch Hunt

### ISSUE THREAD

**Issue by cezaro40** [kgar/foundry-vtt-tidy-5e-sheets#632]
HI,
Steinhardts guide got updated lately so that Trick Weapons (Item specific to that module) use system-provided item subtype to display within Actor inventories and be removed from the "Container" row.

Still Trick Weapons are not showing themselves in the tidy 5e inventory.
After some inquiry with the dev of the steinhardts module for vtt i got a reply.

> the system provides metadata information which the trick weapons now use in order to inform sheet applications what and where to display.

> TidySheet` will need to update to use that new metadata, then all should be well

And so i am asking if this is possible and possibly a rather simple matter or is it a complicated one that requires lots of attention and therefore unnatainable for some time? 

Below i am attaching screen of trick weapon showing up in the base foundry character sheet and it not showing anywhere in the tidy 5e
![obraz_2024-06-04_235820032](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/79403297/b0ba050b-4461-474c-857f-458e85458e7a)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/79403297/ccd77f14-d0fa-4c96-86ce-4c0717c6c397)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/79403297/28383a5b-a95f-43ea-b9fc-4dc7a1ffaaf8)

**Comment by kgar** [comment]
Hello, thanks for trying out the sheets. 
I will certainly give it a try!

**Comment by kgar** [comment]
Could you ask them to be more specific about where to find the metadata? I'm also checking the wiki documentation in the meantime.

**Comment by kgar** [comment]
I think I found what they were talking about. Pasting it here so I can come back to it while working on the fix:

```js
    const inventory = {};
    const inventoryTypes = Object.entries(CONFIG.Item.dataModels)
      .filter(([, model]) => model.metadata?.inventoryItem)
      .sort(([, lhs], [, rhs]) => (lhs.metadata.inventoryOrder - rhs.metadata.inventoryOrder));
    for ( const [type] of inventoryTypes ) {
      inventory[type] = {label: `${CONFIG.Item.typeLabels[type]}Pl`, items: [], dataset: {type}};
    }
```

Tidy doesn't do it this way, currently, but it absolutely should. It may take me a week to make sure I get it right, because dev time is limited.

**Comment by cezaro40** [comment]
I was not expecting that quick of a reply, Thank you for taking notice, Waiting patiently for the fix!
Tidy 5e is my favorite way to interact with the sheet usually and inability to use trick weapons was the only reason i did not really use it past few months.

**Comment by kgar** [comment]
Progress report: switching over Tidy's old code to use the techniques mentioned by the Steinhardt developer seems to be going well. I have some cleaning up, organizing, and testing to do, and then I'll work toward releasing a Tidy update to dnd5e 3.2.x.

One caveat: Trick Weapons will most likely have to use the default sheet, because I have to specifically create sheets to support a particular item type. That's a different discussion, but for now, my goal is to ensure that Trick Items show up on your actor sheets.

**Comment by kgar** [comment]
Tidy v4.3.0, give it a shot when able and see if Trick Weapons show up in the inventory.
