### ISSUE TITLE
compat: Walled Templates

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#656]
Walled Templates 0.8+ on Foundry V12 has a tab on the Item Sheet.
Work with the module author to determine if we can establish compatibility.

https://foundryvtt.com/packages/walledtemplates
https://github.com/caewok/fvtt-walled-templates

**Comment by caewok** [comment]
Added in Walled Templates v0.8.1.

**Comment by kgar** [comment]
Thank you caewok and morepurplemorebetter!
