### ISSUE TITLE
[BUG] Monk's Sound Enhancements button missing from Tidy sheet.

### ISSUE THREAD

**Issue by Janner3D** [kgar/foundry-vtt-tidy-5e-sheets#660]
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/35965176/01b0aa82-7281-47eb-9643-8dd9ba7559da)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/35965176/8f6edfe8-f9a1-4edd-931b-84d40aa8f60d)
The sound button for Monk's Sound Enhancement appears to be missing in Tidy Sheet

**Comment by kgar** [comment]
I have an existing issue for this at #449

I posted to Monk's repo and haven't heard back in 4 months, so far.

**Comment by kgar** [comment]
Monk came through in 4.1.x.
