### ISSUE TITLE
Can't enable module

### ISSUE THREAD

**Issue by SwordofSpirit** [kgar/foundry-vtt-tidy-5e-sheets#664]
Foundry 12.329
D&D 5e 3.3.0
Tidy 5e Sheets 4.4.2

Freshly created world.
No other modules installed.
I check the box to enable, click yes.
App reloads.
Module is not enabled (and not even marked as enabled).

**Comment by kgar** [comment]
Thanks for reporting. Compatibility efforts are underway on this issue:

https://github.com/kgar/foundry-vtt-tidy-5e-sheets/issues/663

**Comment by kgar** [comment]
If you would like to test out Tidy in dnd5e 3.3.x right now, I have released a beta:
https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v5.0.0-beta.1

**Comment by kgar** [comment]
Just released: Tidy V5 is compatible with dnd5e 3.3.0.
