### ISSUE TITLE
Default Theme at World Scope / "Default Dark Mode" for all Players

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#7]
Establish a "Default Theme" setting at world scope.
By default, it should be set to "Light" to keep with the existing functionality.
When current theme is not specified by the user, it should be set to "Default", meaning it points to whatever is the "Default Theme".

> [!IMPORTANT]
> This means, when the GM sets "Default Theme" to "Dark", all new users will open their sheets for the first time and see it in Dark Mode.

## References

https://discord.com/channels/732325252788387980/1116078321067892796/1130574237833363486

SaltyJ — 07/17/2023 1:57 PM
haha
One thing i would like, as a settings option, is to set the default mode for everyone (Light vs Dark) or even custom when/if implemented
i actually tried doing that myself at one point, broke everything 🙂

kgar — 07/17/2023 1:58 PM
Ah, like a full-on game setting for "Default Dark" for a particular game world?

SaltyJ — 07/17/2023 1:59 PM
yeah. They can still change it to what they want, but it would be nice if i could set the default for new players
Running 3 campaigns with a total of 18 players. gets tedious, especially when they clear cookies.

kgar — 07/17/2023 1:59 PM
Gotcha. I'll copy this idea down and add it to the list for when I get nearer to the finish line. I think it's doable.

SaltyJ — 07/17/2023 1:59 PM
insert "Why does the sheet blind me now" questions.
Danke!

**Comment by p4535992** [comment]
This ticket can be closed. You can use other modules for accompish this like :

- https://foundryvtt.com/packages/module-credits
- https://foundryvtt.com/packages/monks-player-settings
- https://foundryvtt.com/packages/force-client-settings
