### ISSUE TITLE
Compatability with Custom DnD5e encumbrance adjustments

### ISSUE THREAD

**Issue by ChobitsCrazy** [kgar/foundry-vtt-tidy-5e-sheets#701]
Hey Kgar, I opened a ticket on their repo to see if we can get the encumbrance changes from Custom DnD5e to reflect on Tidy. Here is the ticket:
https://github.com/Larkinabout/fvtt-custom-dnd5e/issues/80

Thanks!

**Comment by kgar** [comment]
Thanks for reporting. I'll look into this soon.

**Comment by kgar** [comment]
Looking at this now.

How does the encumbrance customization work with the default sheets?
What should Tidy be doing to match this?

**Comment by kgar** [comment]
The main thing I'm finding with Tidy is that it does not currently visualize the thresholds.
Have you found any other specific issues?

**Comment by ChobitsCrazy** [comment]
From what I found/reported is just that, the visualization of the encumbrance thresholds.

**Comment by kgar** [comment]
Perfect, thank you! I'll get this in the next release.

**Comment by kgar** [comment]
This is now live in Tidy v5.4.3.

**Comment by kgar** [comment]
Closing as completed. If there are additional problems found, let me know on a new issue.
Thanks again for reporting this!
