### ISSUE TITLE
Add Better Spell Level Buttons for DnD 5e

### ISSUE THREAD

**Issue by hateitwtf** [kgar/foundry-vtt-tidy-5e-sheets#72]
dnd5e 2.4.0 broke original Tidy5e sheet built in Better Spell Level Buttons for DnD 5e(looks like small issue with new naming of some used in dialog properties). Will you add this feature to your version?

![Spell_Level_Buttons_for_DnD_5e 1](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/130892079/0414ed02-9eef-4f74-b12b-81c50a5fbe1b)

**Comment by kgar** [comment]
Unfortunately, I cannot add this back into the rewritten module. With the rewrite, I am specifically avoiding Foundry/system changes that do not pertain to the sheets. Dialogs/applications have to be specific to Tidy 5e sheets and something I have to maintain (Sheet Settings, Theme Settings, Actor Origin Summary, etc.). Any other functionality has been intentionally excluded, such as exhaustion automation, spell level buttons, and module integration options for Midi QoL / Actions list / etc.

I am glad to apply a fix to the original Tidy sheets for now and also to submit a PR to the standalone Spell Level Buttons module to bring it up-to-date so it can be used by itself, independent of Tidy sheets.

I apologize for the inconvenience. Limiting the new sheets in this way is vital to keep them maintainable in the long run.

**Comment by kgar** [comment]
Closing as not planned. I will leave it to another module to implement this feature.
