### ISSUE TITLE
feat: Support subtypes for loot items 

### ISSUE THREAD

**Issue by Belodri** [kgar/foundry-vtt-tidy-5e-sheets#728]
## Summary

When a world script or module adds subtypes to loot items, which usually don't have subtypes, the default dnd5e item sheet displays a select field for the subtype while the tidy item sheet doesn't. It'd be awesome for homebrewing and module development if tidy could support this the same way the default sheet does.
And since this is a functionality the default item sheet offers, I don't think adding it to tidy would fall outside the scope of this module.

## Example

Adding a new loot type with subtypes via a world script like this:
```js
CONFIG.DND5E.lootTypes.ingredient = {
    label: "Ingredient",
    subtypes: {
        bodyPart: "Body Part",
        herb: "Herb"
    }
}
```
The default item sheet displays the selection field for the subtypes if the lootType has subtypes:
![image](https://github.com/user-attachments/assets/ac116131-e497-41cc-b9c4-93245c448a53)

And hides the selection field if the lootType doesn't have any subtypes:
![image](https://github.com/user-attachments/assets/11056fe9-6f3c-4845-80f2-5797145fe33f)

While the tidy item sheet never displays a selection field for the added subtypes:
![image](https://github.com/user-attachments/assets/525af6f3-645d-42e6-a93f-d5f7968b15f2)

**Comment by kgar** [comment]
Tidy v5.6.0 🎉
