### ISSUE TITLE
Sheet opening as blank and cannot close?

### ISSUE THREAD

**Issue by YungGodChris** [kgar/foundry-vtt-tidy-5e-sheets#735]
![Screenshot 2024-08-24 124950](https://github.com/user-attachments/assets/c5c41cfc-051b-40c9-950c-e118650a097e)
Updated today to the 5.6.0 version and have had this issue where the sheet opens as a blank and when I hit close on it the sheet glitches and just stays there. Any ideas what could be going on?

**Comment by YungGodChris** [comment]
Forgot to add, even with all modules off it still seems to be doing this

**Comment by kgar** [comment]
Can you check to see if there are any errors in the devtools console? If there are, can you take a screenshot and post them here?

**Comment by YungGodChris** [comment]
![Screenshot 2024-08-24 130012](https://github.com/user-attachments/assets/15390243-bd4b-46e7-ac07-3cdf17638626)
This is what pops up in the console when opening the sheet

**Comment by kgar** [comment]
For now, it would be best to roll back to latest Tidy V5.5.x until I  can apply a patch fix. Will be at least several hours from now.

What browser are you using?

**Comment by kgar** [comment]
Thank you for reporting the error!

**Comment by YungGodChris** [comment]
> For now, it would be best to roll back to latest Tidy V5.5.x until I can apply a patch fix. Will be at least several hours from now.
> 
> What browser are you using?

Currently using Opera Gx in these screenshots. Will roll back for now and thank you for the quick responses! Much love for the module

**Comment by YungGodChris** [comment]
Upon further review it might just be a problem with Opera. Opened it in Chrome and it worked just fine. How strange

**Comment by kgar** [comment]
Thanks! I will apply a fix that restores functionality in Opera GX. The specific error is avoidable if I take a different approach.

**Comment by kgar** [comment]
Try again on Tidy 5.6.1 when able.

**Comment by YungGodChris** [comment]
The fix works! Thank you so much <3

**Comment by kgar** [comment]
Glad to get it resolved! Happy gaming!
