### ISSUE TITLE
[Bug] Error when assigning spells to classes

### ISSUE THREAD

**Issue by crash1115** [kgar/foundry-vtt-tidy-5e-sheets#741]
In the spellbook tab, clicking on Tools > Assign Spells to Classes produces an error and doesn't let you assign spells to classes.

Foundry v12.331
dnd5e v3.3.1
Tidy v5.6.2

![image](https://github.com/user-attachments/assets/0d29c636-aea4-4038-a7a7-73fe9d5f22f2)

**Comment by kgar** [comment]
I can't repro, unfortunately.
Can you check to see if this is possibly a module interaction or some data-specific thing that needs accounting for?

When I do this from my dev world, I'm not seeing an error with a spellcaster:
![image](https://github.com/user-attachments/assets/23a76e77-0d1b-4b18-89f7-e28b0cbb8caf)

Even a nonspellcaster like Randal doesn't have issues:
![image](https://github.com/user-attachments/assets/510df75b-f7fe-491b-a871-ef2678cd7d15)

**Comment by crash1115** [comment]
I'll try to follow up this evening, will post my findings shortly!

**Comment by crash1115** [comment]
So I've tested on:
- My dev world and a fresh world (self hosted on win 10)
- No other modules enabled
- Both running the versions listed in the original post
- As both a GM and a player
- On the Foundry app, Chrome, and Firefox

In every combination of those things, it's happening to every actor in these two worlds. That includes:
- Preexisting actors that have been imported from other worlds (and may have weird data baggage)
- Freshly imported starter heroes (with no weird data baggage, theoretically)
- Actors created from scratch with nothing on them
- Actors created from scratch with wizard class and evocation school subclass dragged from SRD compendium

This happens regardless of whether or not the actor has any spells in the spellbook. I tried messing with the class' spellcasting settings - half caster/full caster/etc and spellcasting ability - but no dice. I tried with and without spells in the spellbook. I tried with and without spell slots. None of these things appeared to make a difference.

I tested on a completely different wold, not hosted by me, where I'm a player, and things seemed to work fine. Go figure, lol.

I've attached a few actors for you to take a peek at, but if you need to jump into my world, shoot me a DM on discord whenever you have time to take a look, and I can get you login info.

[fvtt-Actor-from-campaign-world-TdRQfWsgcfjjWPYv.json](https://github.com/user-attachments/files/16768518/fvtt-Actor-from-campaign-world-TdRQfWsgcfjjWPYv.json)
[fvtt-Actor-from-scratch-blank-(dev)-rtCEbqgcFYs5N8Pw.json](https://github.com/user-attachments/files/16768519/fvtt-Actor-from-scratch-blank-.dev.-rtCEbqgcFYs5N8Pw.json)
[fvtt-Actor-from-scratch-w-class-(dev)-eyzeykfQgAAIdTaU.json](https://github.com/user-attachments/files/16768520/fvtt-Actor-from-scratch-w-class-.dev.-eyzeykfQgAAIdTaU.json)
[fvtt-Actor-merric-fresh-(dev)-TYlVW0WwEzgOshsg.json](https://github.com/user-attachments/files/16768521/fvtt-Actor-merric-fresh-.dev.-TYlVW0WwEzgOshsg.json)

**Comment by kgar** [comment]
We fixed it!
