### ISSUE TITLE
Error thrown when vehicle sheets opened; Causes eventual crash needing browser reload

### ISSUE THREAD

**Issue by DnDTinkerCrab** [kgar/foundry-vtt-tidy-5e-sheets#761]
Hello,

I'm experiencing a series of odd console errors when I open up vehicle sheets and try to edit vehicle equipment:

tidy5e-sheet | Failed to render svelte tab TypeError: store.subscribe is not a function
Uncaught (in promise) TypeError: text2 is undefined

This error is thrown both with multiple modules active as well as when it's the only module active. The error eventually causes the vehicle sheet to stop displaying tab data under the various tabs and then finally causes the sheet to lock up and become unresponsive. A browser refresh fixes the issue. To reproduce, create a vehicle sheet containing a vehicle equipment item. Begin editing the item and transitioning to another tab in the sheet. Eventually, these errors start accumulating and after about 4 thrown errors, the sheet becomes unresponsive. Let me know if you need any more information regarding this bug.

Edit:
Foundry version: 11.315
5e version: 3.3.1
Tidy Version: 5.7.3

With an empty vehicle sheet. no error is thrown moving through the tabs. Using the add button under equipment does not throw the error.
when I right click to edit the newly made equipment, the "tidy5e-sheet | Failed to render svelte tab TypeError: store.subscribe is not a function" error is thrown. Moving through the tabs in the equipment sheet at this point does not throw additional errors. Editing the description box and then hitting the save button throws this expanded text2 error:

Uncaught (in promise) TypeError: text2 is undefined

This error was thrown both with all my modules loaded and isolated to Tidy 5e Sheets. The effect was reproduceable in both newly made blank vehicle sheets and previously made sheets. It seems the text2 error is what causes the sheet to crash.

**Comment by kgar** [comment]
Can you post your Foundry version, dnd5e version, and Tidy version?

Does it happen to all vehicles?
What about with an empty vehicle sheet?

**Comment by kgar** [comment]
Also, what browser and hosting setup?

**Comment by DnDTinkerCrab** [comment]
Comment edited above. In short, it looks like hitting save after editing a field throws a text2 error that crashes the sheet on both old sheets and newly created sheets with an equipment added to its inventory that is subsequently edited

**Comment by kgar** [comment]
Thanks for the info. I'll be in touch after an initial diagnosis

**Comment by kgar** [comment]
I found the issue and fixed it. Try Tidy v5.7.4 and let me know if things are good or still broken.

Thank you for reporting the issue!

**Comment by kgar** [comment]
Closing as completed.
