### ISSUE TITLE
New text enrichers are ilegible while using dark theme

### ISSUE THREAD

**Issue by imivoltz** [kgar/foundry-vtt-tidy-5e-sheets#78]
New text enrichers added in the update 2.4.0 see; (https://github.com/foundryvtt/dnd5e/wiki/Enrichers) are very difficult to read while using the dark theme.

![image](https://github.com/sdenec/tidy5e-sheet/assets/74024189/3e46453f-4ccf-408f-b1ae-dce1078cf8d3)

Old enrichers (those that used the [[/r]] formula) are displayed just fine as shown in the attached image.

**Foundry version:** Version 11 Build 315
**Dnd5e version:** 2.4.0
**Tidy5e version:** 0.1.10

**Comment by kgar** [comment]
Thank you for reporting this! Got a fix shipping soon: 

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/6ca2213b-d13c-4e81-94ea-bd155a3ee099)

**Comment by kgar** [comment]
New release is out. Have a look and feel free to close the issue if resolved.
