### ISSUE TITLE
Enrichers overlap on defult settings

### ISSUE THREAD

**Issue by imivoltz** [kgar/foundry-vtt-tidy-5e-sheets#80]
While using the default font and settings provided, if enrichers are too close to each other on adjacent paragraphs they overlap. Maybe some kind of indentation could be added for a cleaner look.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/74024189/5d305c76-f1b8-436c-bb39-a65035ee0b37)

**Diary** entries on player character sheets do this somewhat already, maybe try to emulate the style provided there:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/74024189/ab9c8af9-9ebf-4d8e-b45e-b635a72cf435)

Foundry version: Version 11 Build 315
Dnd5e version: 2.4.0
Tidy5e version: 0.1.11

**Comment by kgar** [comment]
Can you copy your text from those editors and paste them in a comment here on github? I'd like to use them while updating the styles.

**Comment by imivoltz** [comment]
Una ola de energía sagrada sobrecarga tu cuerpo y explota en un área de 15 pies a tu alrededor. Las criaturas atrapadas en la explosión deben superar una tirada de salvación de [[/save con dc=@attributes.spelldc]] o sufrir [[/damage formula=2d8 type=Radiant]] de daño radiante y quedar @UUID[Compendium.warcraft-compendium.reglas.JournalEntry.4BLwhynrXF9bMyso.JournalEntryPage.xyUEqUbDwBAWIAel]{Cegados} hasta el final de tu próximo turno si fallan la salvación, o la mitad de daño si tiene éxito.

**Comment by kgar** [comment]
Looking at the default sheet, it looks like overlap is also an issue there: 

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/9ea3acbe-f93a-46e2-85bd-6078cee1aab1)

Increasing the line height of the paragraphs ultimately makes them slightly too spread apart: 

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/b85c5062-4f5f-459d-9d51-66989e08ce2a)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/92edbadc-39d0-4bed-b22f-cb753a9c3a02)
(I had to change the compendium reference so I could visualize an enricher.)

This could take some more time to think through. I may not be able to fix it as quickly as the original issue.

**Comment by imivoltz** [comment]
Not a worry! Thanks for looking into this, i understand it might not be a high priority on the overall!

**Comment by kgar** [comment]
Looking back at this, and looking at how other web applications handle line height and `fields` `like` `this`, I may just increase the line height to a comfortable place that accounts for enricher height. It's the only appropriate thing to do, I think.

Either way, I have a way forward to resolve this issue and will follow up when I've got a proposed fix.

**Comment by kgar** [comment]
What are your thoughts on this line height?

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/1160596e-3f15-49f4-875d-0d1f7332b4f7)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/b0ebd2d3-cb96-407a-84a9-4312a9f48a4d)

**Comment by kgar** [comment]
The latest release is now here with the increased line heights:
https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v0.2.6

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/ffe41e54-ab57-435b-9879-ff6ba0db7183)

Closing issue as resolved. If you have any additional issues, feel free to reopen this github issue.
