### ISSUE TITLE
Item card not minimizing when dragging and dropping an item to target

### ISSUE THREAD

**Issue by gambit07** [kgar/foundry-vtt-tidy-5e-sheets#81]
Including a video because I think it should be easier to show that way

https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4236874/eadd6dc1-77cd-465c-ab80-7172050208c3

**Comment by kgar** [comment]
Good catch. I was able to draw inspiration from the original Tidy sheets for the fix. Should be released tomorrow.

**Comment by kgar** [comment]
The fix has been released in 0.1.14. Have a look when able, and feel free to close the issue if things are good to go.

**Comment by gambit07** [comment]
Thank you sir, all good!
