### ISSUE TITLE
[BUG] Hovering and Editing an unidentified object in a container causes the Sheet to become unresponsive.

### ISSUE THREAD

**Issue by szefo09** [kgar/foundry-vtt-tidy-5e-sheets#816]
Hi, during my game my player discovered, that when checking an unidentified magic item in their bag, their sheet became unresponsive and buggy.

It seems to have to do with hovering/editing an unidentified item that doesn't have a description.
System: Foundry V12, D&D 5e 3.3.1
Tidy5e: 5.10.1

Steps that caused the issue for us:
Have a container with an item. (The item doesn't have an unidentified description)
Unidentify it, and hover over it in the container's menu.
Try to edit it and click on the description and details tab.
Currently the window becomes buggy and I cannot seem to close it, it requires page refresh to remove it.

![{5E65CE34-A2FB-4F91-A609-23F9AC78E16E}](https://github.com/user-attachments/assets/4f6dfad6-1d3d-41b6-aa90-794248995eab)
![{FA7B89CE-586C-4854-8F65-620ABB21E813}](https://github.com/user-attachments/assets/20212e04-4923-492d-ba5e-d06bab8a23ad)

**Comment by kgar** [comment]
Hey friend! 👋

Thanks for reporting.

I ran this test in the same Foundry / dnd5e / Tidy version. I'm able to hover over an unidentified item in a bag. 

From a container on a sidebar:
![image](https://github.com/user-attachments/assets/52ec0879-0b92-4459-8974-1e964f44e21e)

From a PC:
![image](https://github.com/user-attachments/assets/17eb1e5d-73b1-47aa-8eb3-396e5c932ed0)

I'll need some more help with reproducing this error.

Is there a specific item that triggers it? 
Does it trigger consistently?
Does it trigger when Tidy is the only module enabled? If it does not trigger in this scenario, let's figure out which module Tidy is having issues integrating with, and we can probably figure something out.

If you are willing, can you export the actor that's experiencing the issue. You can send to me privately on discord, if you'd like. I might be able to trigger it based on data. If it is a data issue, then that's something I can probably fix in Tidy 🤞

**Comment by kgar** [comment]
Note: I did test with empty descriptions, also:
![image](https://github.com/user-attachments/assets/ccfb2c55-89b0-4a2c-ba98-cf7bbdaceec4)

I believe the error is unrelated to description. When the item card tried to pull the description to show it, the item itself was undefined, which triggered the error.

**Comment by szefo09** [comment]
Hey there, thank you for investigating the issue! 
After further testing, and disabling every other module I noticed a thing.
Have you tried to replicate the issue as a GM or as a player? This seem to affect me only if I login as a player of mine, and it's very consistent, no matter the container/item.

**Comment by kgar** [comment]
My tests were as a player.

**Comment by kgar** [comment]
Can you try this on a fresh world?
