### ISSUE TITLE
Tidy 5e sheets are stated not compatible with Dnd 5e 4.1.0

### ISSUE THREAD

**Issue by Claivain** [kgar/foundry-vtt-tidy-5e-sheets#826]
I updated to DnD 4.1.0 without thinking, and now Tidy 5e sheets don't work (I can't even activate it, it says not compatible). This means I cannot import my characters using the DnD importer either :(

**Comment by kgar** [comment]
Thanks for reporting!
I started compatibility efforts yesterday.

If you have no other choice, I have a beta release which unlocks Tidy for 4.1.0: https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v6.5.0-beta.1

Bastion content is missing on Tidy sheets, and there are some unseen technical updates that are required. Thus far, those are the only issues I've identified.

Here is the beta URL for installation: https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/download/v6.5.0-beta.1/module.json

If you come across issues, feel free to post them here.

**Comment by Claivain** [comment]
Thanks for the reply, it is much appreciated!

**Comment by kgar** [comment]
Next beta is up: https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v7.0.0-beta.2

Install link: https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/download/v7.0.0-beta.2/module.json

Tidy will roll into 4.1.0 soon, and features like the Bastion character tab and Bastion Item Sheet will come later, after Tidy V7 for dnd5e 4.1.0 is already live.

**Comment by kgar** [comment]
We have arrived. Tidy V7 is here.
