### ISSUE TITLE
Toggle Character Sheet Sections

### ISSUE THREAD

**Issue by ZeroXNoxus** [kgar/foundry-vtt-tidy-5e-sheets#855]
I wanted to ask if it would be possible to get a context menu when you right click on the character sheet on the sections (eg. Inventory, Spells, etc.) to hide a section for the character sheet?

I, for example, have a character without any spells and I occasionally click on the spellbook tab only to see an empty section.

This would be a nice feature going down the line.

**Comment by kgar** [comment]
Tidy currently has section visibility settings in the Section Config menu, accessible via the cog toolbar button on most tabs:

![image](https://github.com/user-attachments/assets/48c17e9b-c5f1-4ace-98f4-81fe5c3da664)

![image](https://github.com/user-attachments/assets/0227a4b9-5ef3-4d00-b8a3-e500cefed257)


But also, for the case of having no spells, you can even hide the Spellbook tab altogether with Tab Selection:

![image](https://github.com/user-attachments/assets/67f562a5-7464-497a-897c-b6438247a0e5)

![image](https://github.com/user-attachments/assets/19752e9b-7ca1-494b-90cb-6867de2e4808)

**Comment by ZeroXNoxus** [comment]
Oh, I haven't seen this option, thanks for the hint and clarification!

**Comment by kgar** [comment]
I'm glad I could help out this time. Happy gaming!
