### ISSUE TITLE
Issue with duplicating Reveal/Hide text when editing an item's activities.

### ISSUE THREAD

**Issue by TouchfuzzyGH** [kgar/foundry-vtt-tidy-5e-sheets#862]
Foundry Virtual Tabletop: Version 12 Stable
Build: 331
DnD5e: 4.1.2

Active Modules: 2
1. Players Handbook (2024)
2. Tidy 5e Sheets 7.1.0

I'm having an issue where, when I pull an item out with activities (in this instance, a set of ball bearings), if I click on the activities to edit them, it duplicates the Reveal/Hide text header.  However, if I switch the item sheet from the Tidy 5e Classic Item Sheet to the default 5e one, the Reveal/Hide text no longer gets duplicated.  The duplication happens on both the default character sheet and the Tidy5e character sheet; only switching the item sheet causes or fixes this issue for me.

https://github.com/user-attachments/assets/93ad8e8b-ebca-4e44-9b2a-e14c76c21aa2

**Comment by kgar** [comment]
Thanks for reporting. I'll start looking into this.

**Comment by kgar** [comment]
I was able to find the issue. I'll be issuing a fix as soon as I'm able. It'll be in Tidy v7.2.1

**Comment by kgar** [comment]
The fix is live on Tidy V7.2.1

**Comment by kgar** [comment]
Cheers
