### ISSUE TITLE
Spell tab not rendering on multi class spell users

### ISSUE THREAD

**Issue by ctbritt** [kgar/foundry-vtt-tidy-5e-sheets#872]
![CleanShot 2024-12-15 at 10 57 48@2x](https://github.com/user-attachments/assets/86e8aa97-fc19-4e46-a398-b8e7ee2c6e4a)

12.331/4.1.2 all modules off except tidy

**Comment by ctbritt** [comment]
Tidy 7.3.0b2

**Comment by ctbritt** [comment]
ok. seems to be working in b3.

**Comment by kgar** [comment]
Good to hear. Thank you for trying out the betas! My apologies for the mixup on beta 2.

**Comment by kgar** [comment]
Tidy V7.3.0 is now out with all the fixes in place. Thanks again for testing!
