### ISSUE TITLE
Equipment for 5e system shows 0 for bonus and isn't editable

### ISSUE THREAD

**Issue by Desmondchaser27** [kgar/foundry-vtt-tidy-5e-sheets#879]
Whenever a piece of equipment is created or needs to be edited, for some reason the Bonus (which usually manifests as a bonus to AC) is always displayed as 0 and cannot be edited.  This appears to only be an issue with Tidy 5e Sheets.  As whenever I revert to standard 5e sheets the correct value is immediately displayed and editing the value correctly updates it permanently.

Example of what I see in Tidy 5e:
![image](https://github.com/user-attachments/assets/a80cfb04-8842-4627-b9e5-797328c8ecdf)

Example of what it shows when I switch back to Default 5e Sheet:
![image](https://github.com/user-attachments/assets/56898e47-3321-4eb8-a0aa-55b9c5c104b1)

**Comment by kgar** [comment]
Thank you very much for reporting. I will have that fix out within the next day or so.

**Comment by Desmondchaser27** [comment]
No problem.  Thanks.

**Comment by kgar** [comment]
This is now fixed in Tidy 7.3.1.

**Comment by Desmondchaser27** [comment]
> This is now fixed in Tidy 7.3.1.

Really appreciate it.  Tested this morning, working as expected.
